var calenderi18 = { "bizCalAlert10" : "Calendar name should not contain characters like:<, >, \\\", \\\', %, ;, (, ), &, +, \\\\,  comma, : , |, #",
                    "bizCalAlert11" : "La description du calendrier ne devrait pas contenir les caract\u00e8re suivants : <, >, \\\", ', %, ;, (, ), &, +, \\\\",
                    "bizCalAlert12" : "La description du calendrier est trop longue. Elle ne doit pas exc\u00e9der 256 caract\u00e8res.",
                    "bizCalAlert14" : "The Start Time cannot be greater than or equal to the End Time for the Regular Business Hours.",
                    "bizCalAlert15" : "L'heure du d\u00e9but du d\u00eener devrait \u00eatre entre l'heure du d\u00e9but et l'heure de fin des heures r\u00e9guli\u00e8res de bureau.",
                    "bizCalAlert16" : "L'heure de fin du d\u00eener devrait \u00eatre entre l'heure du d\u00e9but et l'heure de fin des heures r\u00e9guli\u00e8res de bureau.",
                    "bizCalAlert17" : "L'heure du d\u00e9but du d\u00eener ne peut pas \u00eatre \u00e9gale ou post\u00e9rieure \u00e0 l'heure de fin du d\u00eener.",
                    "bizCalAlert18" : "L'heure du d\u00e9but du d\u00eener devrait \u00eatre entre l'heure du d\u00e9but et l'heure de fin des heures r\u00e9guli\u00e8res de bureau.",
                    "bizCalAlert19" : "L'heure de fin du d\u00eener devrait \u00eatre entre l'heure du d\u00e9but et l'heure de fin des heures r\u00e9guli\u00e8res de bureau.",
                    "bizCalAlert20" : "Les heures de d\u00e9but et de fin du d\u00eener devraient \u00eatre le m\u00eame jour.",
                    "bizCalAlert21" : "L'intervalle des ann\u00e9es est invalide. Veuillez choisir un intervalle valide.",
                    "bizCalAlert22" : "Veuillez choisir un fuseau horaire.",
                    "bizCalAlert23" : "Il n'y a aucun calendrier marqu\u00e9. Pour pouvoir supprimer, veuillez choisir au moins un calendrier.",
                    "bizCalAlert24" : "\u00cates-vous s\u00fbr de vouloir supprimer?",
                    "bizCalAlert25" : "Le nom du temps non travaill\u00e9 contient une virgule (\",\") qui est un caract\u00e8re invalide. Veuillez entrer un nom valide.",
                    "bizCalAlert42" : "Veuillez entrer le nom",
                    "bizCalAlert43" : "Veuillez choisir un jour pour la fin de semaine",
                    "bizCalAlert44" : "Veuillez choisir une occurrence pour la fin de semaine",
                    "bizCalAlert45" : "La derni\u00e8re occurrence n'est pas valide pour la fin de semaine",
                    "bizCalAlert46":  "Veuillez choisir une option pour le champ Type",
                    "bizCalAlert47":  "Veuillez choisir une option pour le champ Ann\u00e9e",
                    "bizCalAlert48":  "Veuillez choisir une option pour le champ Mois",
                    "bizCalAlert49":  "Veuillez choisir le jour pour le jour f\u00e9ri\u00e9",
                    "bizCalAlert50":  "Veuillez choisir une occurrence pour le jour f\u00e9ri\u00e9",
                    "bizCalAlert51":  "L'occurrence 'Tous' n'est pas valide pour le jour f\u00e9ri\u00e9",
                    "bizCalAlert52":  "Veuillez choisir une date pour le jour f\u00e9ri\u00e9",
                    "bizCalAlert53":  "Veuillez choisir une date pour le jour f\u00e9ri\u00e9",
                    "bizCalAlert54":  "The Start Time cannot be greater than or equal to the End Time for the Special Business Hours.",
                    "bizCalAlert55":  "Le temps de travail de ce jour ou de cette date existe d\u00e9j\u00e0. Voulez-vous le remplacer?",
                    "bizCalAlert56":  "La description du calendrier ne doit pas contenir des caract\u00e8res comme : <, >, \\\",\\\\",
                    "bizCalAlert57":  "Veuillez choisir un temps de travail \u00e0 supprimer.",
                    "bizCalAlert58":  "\u00cates-vous s\u00fbr de vouloir supprimer ce temps de travail? " ,
                    "bizCalAlert59":  "Veuillez choisir un jour f\u00e9ri\u00e9 \u00e0 supprimer.",
                    "bizCalAlert60":  "\u00cates-vous s\u00fbr de vouloir supprimer ce temps non travaill\u00e9? ",
                    "bizCalAlert61":  "Un temps non travaill\u00e9 existe d\u00e9j\u00e0 avec ce nom.",
                    "bizCalAlert62":  "Un temps non travaill\u00e9 existe d\u00e9j\u00e0 pour ce jour ou cette date.",
                    "bizCalAlert63": "Non-working Time name contains dollar symbol (\"$\") which is an invalid character. Please enter a valid name.",
                    "bizCalAlert64": "Non-Working time already exists in the selected date",
                    "bizCalAlert65": "Working time already exists in the selected date"
};
