var calenderi18 = { "bizCalAlert10" : "Calendar name should not contain characters like:<, >, \\\", \\\', %, ;, (, ), &, +, \\\\,  comma, : , |, #",
                    "bizCalAlert11" : "Calendar description should not contain characters like:<, >, \\\", \\\', %, ;, (, ), &, +, \\\\",
                    "bizCalAlert12" : "Calendar description is too long. Maximum characters allowed is 256.",
                    "bizCalAlert14" : "The Start Time cannot be greater than or equal to the End Time for the Regular Business Hours.",
                    "bizCalAlert15" : "The Mid-Day Break Start Time should be between Start Time and End Time of the Regular Business Hours.",
                    "bizCalAlert16" : "The Mid-Day Break End Time should be between Start Time and End Time of the Regular Business Hours.",
                    "bizCalAlert17" : "The Start Time cannot greater than or equal to the End Time for the Mid-Day Break.",
                    "bizCalAlert18" : "The Mid-Day Break Start Time should be between Start Time and End Time of the Regular Business Hours.",
                    "bizCalAlert19" : "The Mid-Day Break End Time should be between Start Time and End Time of the Regular Business Hours.",
                    "bizCalAlert20" : "The Start Time and the End Time of the Mid-Day Break should be on the same day.",
                    "bizCalAlert21" : "Invalid Year range specified.Please select proper range",
                    "bizCalAlert22" : "Please select a timezone.",
                    "bizCalAlert23" : "There is no CHECKED calendar. For delete operation please select at least one calendar",
                    "bizCalAlert24" : "Are you sure you want to delete the selected calendars?",
                    "bizCalAlert25" : "Non-working Time name contains comma(\",\") which is an invalid character. Please enter a valid name.",
                    "bizCalAlert42" : "Please enter the name",
                    "bizCalAlert43" : "Please select day for the weekend",
                    "bizCalAlert44" : "Please select occurrence for the weekend",
                    "bizCalAlert45" : "Occurrence 'Last' is not valid for the weekend",
                    "bizCalAlert46":  "Please select option for Type field",
                    "bizCalAlert47":  "Please select option for Year field",
                    "bizCalAlert48":  "Please select option for Month field",
                    "bizCalAlert49":  "Please select day for the holiday",
                    "bizCalAlert50":  "Please select occurrence for the holiday",
                    "bizCalAlert51":  "Occurrence 'All' is not valid for the holiday",
                    "bizCalAlert52":  "Please select date for the holiday",
                    "bizCalAlert53":  "Please select date for the holiday",
                    "bizCalAlert54":  "The Start Time cannot be greater than or equal to the End Time for the Special Business Hours.",
                    "bizCalAlert55":  "Working time for this day/date already exists. Do you want to overwrite?",
                    "bizCalAlert56":  "Calendar description should not contain characters like:<, >, \\\",\\\\",
                    "bizCalAlert57":  "Please select a working time to delete!",
                    "bizCalAlert58":  "Are you sure you want to delete working time? " ,
                    "bizCalAlert59":  "Please select an holiday to delete!",
                    "bizCalAlert60":  "Are you sure you want to delete non-working time? ",
                    "bizCalAlert61":  "Non-Working time with this name already exists",
                    "bizCalAlert62":  "Non-Working time for this day/date already exists",
                    "bizCalAlert63": "Non-working Time name contains dollar symbol (\"$\") which is an invalid character. Please enter a valid name.",
                    "bizCalAlert64": "Non-Working time already exists in the selected date",
                    "bizCalAlert65": "Working time already exists in the selected date"
                    
                  };