
CREATE TABLE BR_PROJECT (
       PROJECT_ID           BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
                            (START WITH 1, INCREMENT BY 1, NO CACHE),
       PROJECT_NAME         VARCHAR(64) NOT NULL ,
       PROJECT_VERSION      INTEGER NOT NULL,
       DESCRIPTION          VARCHAR(255),
       PROJECT_STATUS       VARCHAR(12) NOT NULL,
       PROJECT_CATEGORY     VARCHAR(64),
       PARENT_ID            BIGINT DEFAULT -1,
       CREATED_BY           VARCHAR(128),       
       CREATED_DATE         TIMESTAMP,
       MODIFIED_BY          VARCHAR(128),
       MODIFIED_DATE        TIMESTAMP
);

CREATE UNIQUE INDEX IX_BR_PROJECT_1 ON BR_PROJECT (
    PROJECT_NAME, 
    PROJECT_VERSION
);


CREATE TABLE BR_RULESET (
       RULESET_ID           BIGINT PRIMARY KEY  GENERATED ALWAYS AS IDENTITY 
                            (START WITH 1, INCREMENT BY 1, NO CACHE),
       RULESET_NAME         VARCHAR(64) NOT NULL,
       DESCRIPTION          VARCHAR(255),
       RULE_TYPE            VARCHAR(4),
       RULE_CONTENT         BLOB(256M) NOT LOGGED COMPACT DEFAULT NULL,
       PROJECT_ID           BIGINT NOT NULL,
       RULESET_STATUS       VARCHAR(12) NOT NULL,
       RULESET_CATEGORY     VARCHAR(64),
       PROPERTIES           BLOB(256M) NOT LOGGED COMPACT DEFAULT NULL,
       CREATED_BY	    	VARCHAR(128),
       CREATED_DATE         TIMESTAMP,
       MODIFIED_BY          VARCHAR(128),
       MODIFIED_DATE        TIMESTAMP 
);

CREATE UNIQUE INDEX IX_BR_RULESET_1 ON BR_RULESET(
    PROJECT_ID, 
    RULESET_NAME
);


CREATE TABLE BR_EXEC_SET (
    EXEC_SET_ID             BIGINT PRIMARY KEY  GENERATED ALWAYS AS IDENTITY 
                            (START WITH 1, INCREMENT BY 1, NO CACHE),
    URI                     VARCHAR(255) NOT NULL,
    DESCRIPTION             VARCHAR(255),
    CREATED_BY              VARCHAR(128),
    CREATED_DATE            TIMESTAMP,
    MODIFIED_BY             VARCHAR(128),
    MODIFIED_DATE           TIMESTAMP
);

CREATE UNIQUE INDEX IX_BR_EXEC_SET_1 ON BR_EXEC_SET (
    URI
);

CREATE TABLE BR_EXEC_SET_RULESET_REL (
    EXEC_SET_ID         BIGINT NOT NULL,
    RULESET_ID        	BIGINT NOT NULL,
    CONSTRAINT BR_ES_RS_PKEY PRIMARY KEY(EXEC_SET_ID, RULESET_ID)
);

CREATE INDEX IX_ES_RS_REL_ESID
 ON BR_EXEC_SET_RULESET_REL (EXEC_SET_ID);

CREATE INDEX IX_ES_RS_REL_RSID
 ON BR_EXEC_SET_RULESET_REL (RULESET_ID);
