<%--  This JSP has been generated by using from xsl version 9.0 at Wed Mar 09 17:54:25 IST 2022 --%>
<!DOCTYPE html>
<html xmlns:sbm="http://www.savvion.com/sbm" xmlns:bizsolo="http://www.savvion.com/sbm/BizSolo" xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:xalan="http://xml.apache.org/xalan" xmlns:fn="http://www.w3.org/2005/02/xpath-functions" xmlns:sfe="http://www.savvion.com/sbm/sfe" xmlns:c="http://java.sun.com/jsp/jstl/core">
<head><META http-equiv="Content-Type" content="text/html; charset=utf-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge">

<%@ page contentType="text/html; charset=UTF-8" %>
<%@ page import="com.savvion.BizSolo.Server.*,com.savvion.BizSolo.beans.*,com.savvion.sbm.util.DatabaseMapping,java.util.Vector,java.util.Locale" %>
<%@ page import="com.savvion.sbm.bizsolo.util.session.*,java.net.*" %>
<%@ page errorPage="/BizSolo/common/jsp/expcontroller.jsp" %>
<%@ taglib uri="/BizSolo/common/tlds/bizsolo.tld" prefix="bizsolo" %>
<%@ taglib uri="/bpmportal/tld/bpmportal.tld" prefix="sbm" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib prefix="form" tagdir="/WEB-INF/tags/form"%>
<%@ taglib prefix="sfe" uri="http://jmaki/v1.0/jsp" %>
  <jsp:useBean id="bizManage" class="com.savvion.sbm.bizmanage.api.BizManageBean" scope="session"></jsp:useBean>
  <jsp:useBean id="bean" class="com.savvion.BizSolo.beans.Bean" scope="session"></jsp:useBean>
  <jsp:useBean id="factoryBean" class="com.savvion.BizSolo.beans.EPFactoryBean" scope="session"></jsp:useBean>
  <jsp:useBean id="bizSite" class="com.savvion.sbm.bpmportal.bizsite.api.BizSiteBean" scope="session"></jsp:useBean>
<%! String _PageName = "InitiateFlow"; %>
<%! String __webAppName = "Marcom_OnlineFlow"; %>
<% pageContext.setAttribute( "contextPath", request.getContextPath()+"/"); %>
<% pageContext.setAttribute( "maxMultiLineLength", DatabaseMapping.self().getSQLSize(java.lang.String.class));  %>
<%java.util.List<String> priorities = com.savvion.sbm.bpmportal.util.PortalUtil.self().getPriorities();%>
<% pageContext.setAttribute( "_priorities",priorities); %>
<bizsolo:if test='<%=_PageName.equals(request.getParameter("_PageName")) %>'>
    <bizsolo:setDS name="application,category,subCategory,userRemarks,userUpload"></bizsolo:setDS>
    <bizsolo:setDS name="bizsite_instanceName,bizsite_priority"></bizsolo:setDS>
    <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKCreatePI" perfMethod="commit" mode="BizSite" dsi="userUpload,userRemarks,subCategory,category,application"></bizsolo:executeAction>
<% /* Workaround, retAddr will disappear in the future */ %>
<% String retAddr = bean.getPropString("returnPage"); %>
<% if(retAddr != null) { %>
<bizsolo:redirectURL page="<%= retAddr %>"/>
<% } %>
</bizsolo:if>
<bizsolo:if test='<%= ! _PageName.equals(request.getParameter("_PageName")) %>'>
    <bizsolo:initApp mode="BizSite" name="Marcom_OnlineFlow" refresh="true"></bizsolo:initApp>
    <bizsolo:initDS name="bizsite_instruction"></bizsolo:initDS>
    <bizsolo:initDS name="bizsite_priority" hexval="FALSE"></bizsolo:initDS>
    <bizsolo:initDS name="bizsite_instanceName" hexval="FALSE"></bizsolo:initDS>
<bizsolo:initDS name="application" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="category" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="subCategory" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="userRemarks" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="userUpload" type="DOCUMENT"></bizsolo:initDS>
    <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKGetDS" perfMethod="commit" mode="BizSite" dso="userUpload,userRemarks,subCategory,category,application"></bizsolo:executeAction>
</bizsolo:if>

<title>InitiateFlow</title>
<%boolean isStandaloneBS = (bizManage == null || bizManage.getName() == null || "".equals(bizManage.getName()) || bizManage.getLocale() == null);Locale myLocale = (!isStandaloneBS) ? bizManage.getLocale() : request.getLocale();%>
<!-- Javascript -->
<script language="JavaScript"> var getLocalizedString = parent.getLocalizedString; </script>
<form:includes contextPath="${contextPath}"/>
<script language="JavaScript">
     
      var isIFrame = <%= (PublicResources.INTERACTIVE_MODE.equalsIgnoreCase(bean.getPropString(PublicResources.MODE)) || PublicResources.SLAVE_MODE.equalsIgnoreCase(bean.getPropString(PublicResources.MODE))) ? true : false %>;
      

    function getContextPath(){
        return "<%=request.getContextPath()%>";
    }
</script>


<sbm:setLocale value="<%= bizManage.getLocale() %>"></sbm:setLocale>
<% try{ %><sbm:setBundle scope="page" basename="Marcom_OnlineFlow/properties/Marcom_OnlineFlow"></sbm:setBundle><% } catch(Exception e){}%>
<bizsolo:getApplicationResources baseName="Marcom_OnlineFlow/properties/Marcom_OnlineFlow"/></head>
<body class="apbody yui-skin-sam" onLoad="setCheckBoxStyleForIE();hideControls();beforeInitControls();initControls();initTabs();sbm.utils.onDOMReady();">
<form method="post" name="form" onsubmit="return sbm.utils.onFormSubmit();">
<div id="northDiv" style="height:0px;display:none;"><bizsolo:xsrf/></div><% /* Workaround, activityName will disappear in the future */ %>
<% String activityName = bean.getPropString("workitemName"); %>
<div id="resultDiv">
<div style='visibility:hidden;display:none' class='vBoxClass' name='errors' id='errors'></div>
<input name="_PageName" type="hidden" value="InitiateFlow">
<%if(bean.getPropString("workitemName") != null) {%><input name="_WorkitemName" type="hidden" value="<%= URLHexCoder.encode(bean.getPropString("workitemName")) %>"/><input name="_WorkitemId" type="hidden" value="<%= bean.getPropLong("workitemId") %>"/><%}%>
<input name="bizsite_pagetype" type="hidden" value="start">
<input name="_ProcessTemplateName" type="hidden" value='<%=bean.getPropString("ptName")%>'>
<input name="_yahoo_flow_button" type="hidden" value=''>
<!-- Content --> 

    
<!-- Header -->
<table width="100%" cellspacing="0" cellpadding="0" border="0">
<tr>
<td class="ApSegTblInBg">
<table border="0" cellspacing="0" align="center" cellpadding="4" width="100%">
<tr align="center">
<td class="ApSegTitle" style="border-top:0px;"><bizsolo:getLabel type="RESOURCE" name="processTemplateLabel_"></bizsolo:getLabel></td>
</tr></table>
<table border="0" cellspacing="1" align="center" cellpadding="4" width="100%" class="ApSegDataTbl">
<tr border="1" align="center">
<td border="1" width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_INSTANCE_NAME_LABEL"></bizsolo:getLabel></td>
<td border="1" width="55%" class="ApSegGenData"><input name="bizsite_instanceName" size="30" maxlength="240" type="text" class="ApInptTxt"><script>addValue("bizsite_instanceName", "<bizsolo:getLabel type='RESOURCE' name='processTemplateLabel_'/>");</script></td>
<td border="1" width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_PRIORITY_LABEL"></bizsolo:getLabel></td>
<td border="1" width="15%" class="ApSegGenData"><select name="bizsite_priority" id="bizsite_priority" class="ApInptSelect"><c:forEach var="priority" items="${_priorities}"> <option value="${priority}"> <c:choose><c:when test="${priority == 'critical'}"><bizsolo:getLabel type="RESOURCE" name="PRIORITY_CRITICAL"/></c:when><c:when test="${priority == 'high'}"><bizsolo:getLabel type="RESOURCE" name="PRIORITY_HIGH"/></c:when><c:when test="${priority == 'medium'}"><bizsolo:getLabel type="RESOURCE" name="PRIORITY_MEDIUM"/></c:when><c:when test="${priority == 'low'}"><bizsolo:getLabel type="RESOURCE" name="PRIORITY_LOW"/></c:when>    </c:choose>    </option>        </c:forEach>  </select></td>
</tr>
<tr><td border="1" width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_INSTRUCTION_LABEL"></bizsolo:getLabel></td>
<td border="1" colspan="3" class="ApSegGenData"><sbm:message key="workstep.InitiateFlow.instruction" escapeLine="true"></sbm:message></td></tr>
</table>
</td>
</tr>
</table>

    <script src='scripts/jquery-1.11.2.js'></script>
<script src='scripts/commonJS.js'></script>
<link rel='stylesheet' href='style/custom.css' />
<link rel='stylesheet' href='style/styles.css' />

<script>

$(function() {
    $('li').click(function(){
       $(this).parent().children().each(function(){
       $(this).css('background-color','#f0f0f0');
       $(this).find('a').first().css('color','#323b42');
      });
       $(this).css('background-color','#005D94');
       $(this).find('a').first().css('color','white');
    }); 
    $('#registerLnk').click(); 
  });

</script>

<div class='master'>
    <div id='nav' style='text-align:center;'> 
    <nav>
	<ul class="fancyNav">
	    <li id="registerLnk"><a>Register Ticket</a><img src='images/Register.jpg' class='liImg' /></li>
	    <li id="trackLnk"><a>Search Ticket</a><img src='images/tracking.png' class='liImg' /></li>
	    <li id="dltLnk"><a>Delete Ticket</a><img src='images/remove_ticket_256.png' class='liImg' /></li>
	</ul>
     </nav>
   </div>  
<div class='registerDiv'></div>
</div>
<div style='display:none;'>
<input type='text' name='bizsite_instanceName' id='bizsite_instanceName' />
    <br clear="all">
<sfe:widget name="sbm.textfield" id="applicationName" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

    <sfe:widget name="sbm.textfield" id="categoryName" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

    <sfe:widget name="sbm.textfield" id="subCategoryName" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

    <sfe:widget name="sbm.textfield" id="userRemark" args="{'type':'text', 'size':20, 'maxlength':2000, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

    <input class="ApScrnButton" name="bizsite_completeTask" id="done" type="submit" tabindex="0" value="<bizsolo:getLabel name='COMPLETE_LABEL' type='RESOURCE'/>" onMouseOut="this.className='ApScrnButton';" onMouseOver="this.className='ApScrnButtonHover';" onClick="clickedButton=this.name;this.onsubmit = new Function('return false');">

    <br clear="all">
</div>
    <br clear="all">
<div id='docs' style='display:none;'>
    <br clear="all">
<div style="display: inline;" id="document1"><bizsolo:getDS type="field" name="userUpload" multiline="true" wsName="InitiateFlow" appendWith="false" isStart="true"></bizsolo:getDS></div>


    <br clear="all">
</div>
    

</div>
<!-- Footer -->

<div id="cmdDiv" style="height:46px;">
<table width="100%" height="100%" cellpadding="0" align="center" cellspacing="0" border="0">
<tr align="center">
<td class="ApButtonDarkBg" width="63%">
<table border="0" cellspacing="0" cellpadding="0">
<tr>
<td class="ApBtnSpace">
<form:button id="bizsite_completeTask" name="bizsite_completeTask" link="CREATE_LABEL" resourceType="RESOURCE"/> </td>
<td class="ApBtnSpace">
<form:button id="bizsite_reset" name="bizsite_reset" link="RESET_LABEL" onclick="sbm.utils.reset" resourceType="RESOURCE"/> </td>
<td class="ApBtnSpace">
<form:button id="btn-cancel" name="btn-cancel" link="CANCEL_LABEL" onclick="sbm.utils.cancel" resourceType="RESOURCE"/> </td>
</tr>
</table>
</td>
</tr>
</table>
</div>

  
                    <div id="resizablepanel" style="display:none">
                        <div class="hd">Alert Dialog</div>
                        <div class="bd"></div>
                        <div class="ft"></div>
                    </div> 
<div id="southDiv" style="height:0px;display:none;"></div></form>
</body>

<script language="JavaScript">
<!--
function beforeInitControls() {
}
-->
</script>
<script language="JavaScript">
<!--
function userValidationJavascript() {
return true;
}
-->
</script>
<sbm:dataSources appName="Marcom_OnlineFlow" appType="bizlogic">
</sbm:dataSources>
<script language="JavaScript">
<!--
function getCategoryList()
{
  var appTyp = $('#appType').val();
  if(appTyp != 'Select')
  {
    pwr.getCategory(appTyp,getCategoryListCB);
  }
  else
  { 
    $('#categryList').removeAttr('disabled');
    $('#categryList').val('Select');  
    $('#categryList').attr('disabled','disabled');
    if($('#subCategryList').val() != 'Select')
    {
      $('#subCategryList').removeAttr('disabled');
      $('#subCategryList').val('Select');  
      $('#subCategryList').attr('disabled','disabled');
    }
    else
    {
      $('#subCategryList').attr('disabled','disabled');
    }
  }
}

function getCategoryListCB(ctgryList){
  $('#categryList').removeAttr('disabled');
  $('#categryList').html('');
  var selectOption = $('<option value="Select">Select</option>');
  $('#categryList').append(selectOption);
  for(var i in ctgryList)
  {
    var newOption = $('<option value="'+i+'">'+ctgryList[i]+'</option>');
    $('#categryList').append(newOption);
  }
}

function getSubCategories()
{
  var appType = $('#appType').val();
  var categry = $('#categryList').val();
  if(appType != 'Select' && categry != 'Select')
  {
    pwr.getSubCategoryList(appType,categry,getSubCategoriesCB);
  }
  else
    { 
      $('#subCategryList').removeAttr('disabled');
      $('#subCategryList').val('Select');  
      $('#subCategryList').attr('disabled','disabled');
  }
}

function getSubCategoriesCB(list)
{
  $('#subCategryList').removeAttr('disabled');
  $('#subCategryList').html('');
  var selectOption = $('<option value="Select">Select</option>');
  $('#subCategryList').append(selectOption);
  for(var i in list)
  {
    var newOption = $('<option value="'+i+'">'+list[i]+'</option>');
    $('#subCategryList').append(newOption);
  }
}

function setDSValues()
{
  if($('#appType').val() == 'Select')
  {
    alert('Please Select Application Type.');
    $('#appType').focus();
    return false;
  }
  if($('#categryList').val() == 'Select')
  {
    alert('Please Select Category.');
    $('#categryList').focus();
    return false;
  }
  if($('#subCategryList').val() == 'Select')
  {
    alert('Please Select Sub Category.');
    $('#subCategryList').focus();
    return false;
  }
  if($('#rmks').val() == null || $('#rmks').val().trim() == '')
  {
    alert('Please Enter Remarks.');
    $('#rmks').focus();
    return false;
  }
  $('#applicationName').val($('#appType option:selected').text());
  $('#categoryName').val($('#categryList option:selected').text());
  $('#subCategoryName').val($('#subCategryList option:selected').text());
  $('#userRemark').val($('#rmks').val());
  $('#done').click();
  $('#registerID').prop('disabled',true);
}

$('#registerLnk').click(function(){
  $('.registerDiv').html('');
  $('.registerDiv').load('RegisterTicket.jsp');
});

$('#dltLnk').click(function(){
  $('.registerDiv').html('');
  $('.registerDiv').load('DeleteTicket.jsp');
});

$('#trackLnk').click(function(){
  $('.registerDiv').html('');
  $('.registerDiv').load('TrackHistry.jsp');
});

$(document).ready(function(){
    //detectIE();
     // var tbl = document.getElementsByTagName("table")[0];
     // if(tbl) tbl.parentNode.removeChild(tbl);
        document.getElementById("cmdDiv").style.display = "none"; 
        var xmlhttp=new XMLHttpRequest();    
        xmlhttp.onreadystatechange=function() 
        {
     	    if (xmlhttp.readyState == 4 && xmlhttp.status == 200) 
            {
                  var val = xmlhttp.responseText.toString().trim();
                  if(val != 'true')
                  {
                      top.location.href ='../../../bpmportal/administration/auth_deny.jsp';     
                  }
            }
        }
        xmlhttp.open("GET","CheckMarcomUser.jsp?userID="+'<%=bizSite.getCurrentUser()%>', false);
        xmlhttp.send();
});
-->
</script>
<!--Initialize extensible widgets.-->
<script language="JavaScript">
<!--
var _dateFormats = {date:'<%=bean.getPropString(PublicResources.JS_CALENDAR_DATE_FORMAT)%>', dateOnly:'<%=bean.getPropString(PublicResources.JS_CALENDAR_DATE_ONLY_FORMAT)%>'};

var allWidgets = [{widget:'applicationName', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'application', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'application', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'categoryName', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'category', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'category', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'subCategoryName', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'subCategory', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'subCategory', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'userRemark', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'userRemarks', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'userRemarks', dataSlotType:'STRING'}, dsType:'STRING', service:'false'}
];
var businessObjects = [];
var formWidgetHandler;
  var def_priority='<%=com.savvion.sbm.util.PriorityHelper.self().getDefaultPriorityAsString()%>';
sbm.utils.onDOMReady = function() {
YAHOO.util.Event.onDOMReady(function(){
  sbm.utils.setPriority('bizsite_priority','<%=com.savvion.sbm.util.PriorityHelper.self().getDefaultPriorityAsString()%>');formWidgetHandler = new FormWidgetHandler(allWidgets,null,{processName:'Marcom_OnlineFlow',processType:'bizlogic',maxMultiLineLength:${maxMultiLineLength},adapletCache:{'user':''}},'<%=request.getParameter(BizSoloRequest.BSS_FIID)%>');
 });
 }
Ext.onReady(function(){
 var task = new Ext.util.DelayedTask(function(){
});
  task.delay(500);
  var viewport = new Bm.util.BmViewport('',{resultComponentXtype:'container'});

});

   
    scrollToErrors = function() {
        var errorsDiv = document.getElementById('errors');
        if(errorsDiv !== null) {
            errorsDiv.scrollIntoView();
        }
    }
    sbm.utils.onFormSubmit = function() {
        if(!formWidgetHandler.validateWidgets()) {
            scrollToErrors();
            return false;
        }
        try{
            if(!userValidationJavascript()) {
                scrollToErrors();
                return false;
            }              
            sbm.utils.handleFormSubmit();
        }catch(e){
            scrollToErrors();
            return false;
        }

                            document.form.action='<%=response.encodeURL("InitiateFlow.jsp")%>';
         if(allWidgets.length > 0)formWidgetHandler.saveDataSlots();
         return true;
}
-->
</script>

</html>