<%--  This JSP has been generated by using from xsl version 9.0 at Wed Mar 09 17:53:23 IST 2022 --%>
<!DOCTYPE html>
<html xmlns:sbm="http://www.savvion.com/sbm" xmlns:bizsolo="http://www.savvion.com/sbm/BizSolo" xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:xalan="http://xml.apache.org/xalan" xmlns:fn="http://www.w3.org/2005/02/xpath-functions" xmlns:sfe="http://www.savvion.com/sbm/sfe" xmlns:c="http://java.sun.com/jsp/jstl/core">
<head><META http-equiv="Content-Type" content="text/html; charset=utf-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge">

<%@ page contentType="text/html; charset=UTF-8" %>
<%@ page import="com.savvion.BizSolo.Server.*,com.savvion.BizSolo.beans.*,com.savvion.sbm.util.DatabaseMapping,java.util.Vector,java.util.Locale" %>
<%@ page import="com.savvion.sbm.bizsolo.util.session.*,java.net.*" %>
<%@ page errorPage="/BizSolo/common/jsp/expcontroller.jsp" %>
<%@ taglib uri="/BizSolo/common/tlds/bizsolo.tld" prefix="bizsolo" %>
<%@ taglib uri="/bpmportal/tld/bpmportal.tld" prefix="sbm" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib prefix="form" tagdir="/WEB-INF/tags/form"%>
<%@ taglib prefix="sfe" uri="http://jmaki/v1.0/jsp" %>
  <jsp:useBean id="bizManage" class="com.savvion.sbm.bizmanage.api.BizManageBean" scope="session"></jsp:useBean>
  <jsp:useBean id="bean" class="com.savvion.BizSolo.beans.Bean" scope="session"></jsp:useBean>
  <jsp:useBean id="factoryBean" class="com.savvion.BizSolo.beans.EPFactoryBean" scope="session"></jsp:useBean>
  <jsp:useBean id="bizSite" class="com.savvion.sbm.bpmportal.bizsite.api.BizSiteBean" scope="session"></jsp:useBean>
<%! String _PageName = "Start"; %>
<%! String __webAppName = "AgentRetentionProcess"; %>
<% pageContext.setAttribute( "contextPath", request.getContextPath()+"/"); %>
<% pageContext.setAttribute( "maxMultiLineLength", DatabaseMapping.self().getSQLSize(java.lang.String.class));  %>
<%java.util.List<String> priorities = com.savvion.sbm.bpmportal.util.PortalUtil.self().getPriorities();%>
<% pageContext.setAttribute( "_priorities",priorities); %>
<bizsolo:if test='<%=_PageName.equals(request.getParameter("_PageName")) %>'>
    <bizsolo:setDS name="agent_code,attrition_probability,business_category,licence_type,claim_TAT_category,policy_gap,sales_category,claim_per_category,sm_level_vintage,time_last_pol,payout_TAT_category,vintage_month,fresh_per,sm_status,business_last_12month,attrition_risk,branch_code,branch_name,sm_code,sm_name,role"></bizsolo:setDS>
    <bizsolo:setDS name="bizsite_instanceName,bizsite_priority"></bizsolo:setDS>
    <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKCreatePI" perfMethod="commit" mode="BizSite" dsi="role,sm_code,sm_name,branch_code,branch_name,agent_code,attrition_probability,business_category,licence_type,claim_TAT_category,policy_gap,sales_category,claim_per_category,sm_level_vintage,time_last_pol,payout_TAT_category,vintage_month,fresh_per,sm_status,business_last_12month,attrition_risk"></bizsolo:executeAction>
<% /* Workaround, retAddr will disappear in the future */ %>
<% String retAddr = bean.getPropString("returnPage"); %>
<% if(retAddr != null) { %>
<bizsolo:redirectURL page="<%= retAddr %>"/>
<% } %>
</bizsolo:if>
<bizsolo:if test='<%= ! _PageName.equals(request.getParameter("_PageName")) %>'>
    <bizsolo:initApp mode="BizSite" name="AgentRetentionProcess" refresh="true"></bizsolo:initApp>
    <bizsolo:initDS name="bizsite_instruction"></bizsolo:initDS>
    <bizsolo:initDS name="bizsite_priority" hexval="FALSE"></bizsolo:initDS>
    <bizsolo:initDS name="bizsite_instanceName" hexval="FALSE"></bizsolo:initDS>
<bizsolo:initDS name="agent_code" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="attrition_probability" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="business_category" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="licence_type" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="claim_TAT_category" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="policy_gap" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="sales_category" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="claim_per_category" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="sm_level_vintage" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="time_last_pol" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="payout_TAT_category" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="vintage_month" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="fresh_per" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="sm_status" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="business_last_12month" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="attrition_risk" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="branch_code" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="branch_name" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="sm_code" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="sm_name" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="role" type="STRING"></bizsolo:initDS>
    <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKGetDS" perfMethod="commit" mode="BizSite" dso="role,sm_code,sm_name,branch_code,branch_name,agent_code,attrition_probability,business_category,licence_type,claim_TAT_category,policy_gap,sales_category,claim_per_category,sm_level_vintage,time_last_pol,payout_TAT_category,vintage_month,fresh_per,sm_status,business_last_12month,attrition_risk"></bizsolo:executeAction>
</bizsolo:if>

<title>Start</title>
<%boolean isStandaloneBS = (bizManage == null || bizManage.getName() == null || "".equals(bizManage.getName()) || bizManage.getLocale() == null);Locale myLocale = (!isStandaloneBS) ? bizManage.getLocale() : request.getLocale();%>
<!-- Javascript -->
<script language="JavaScript"> var getLocalizedString = parent.getLocalizedString; </script>
<form:includes contextPath="${contextPath}"/>
<script language="JavaScript">
     
      var isIFrame = <%= (PublicResources.INTERACTIVE_MODE.equalsIgnoreCase(bean.getPropString(PublicResources.MODE)) || PublicResources.SLAVE_MODE.equalsIgnoreCase(bean.getPropString(PublicResources.MODE))) ? true : false %>;
      

    function getContextPath(){
        return "<%=request.getContextPath()%>";
    }
</script>


<sbm:setLocale value="<%= bizManage.getLocale() %>"></sbm:setLocale>
<% try{ %><sbm:setBundle scope="page" basename="AgentRetentionProcess/properties/AgentRetentionProcess"></sbm:setBundle><% } catch(Exception e){}%>
<bizsolo:getApplicationResources baseName="AgentRetentionProcess/properties/AgentRetentionProcess"/></head>
<body class="apbody yui-skin-sam" onLoad="setCheckBoxStyleForIE();hideControls();beforeInitControls();initControls();initTabs();sbm.utils.onDOMReady();">
<form method="post" name="form" onsubmit="return sbm.utils.onFormSubmit();">
<div id="northDiv" style="height:0px;display:none;"><bizsolo:xsrf/></div><% /* Workaround, activityName will disappear in the future */ %>
<% String activityName = bean.getPropString("workitemName"); %>
<div id="resultDiv">
<div style='visibility:hidden;display:none' class='vBoxClass' name='errors' id='errors'></div>
<input name="_PageName" type="hidden" value="Start">
<%if(bean.getPropString("workitemName") != null) {%><input name="_WorkitemName" type="hidden" value="<%= URLHexCoder.encode(bean.getPropString("workitemName")) %>"/><input name="_WorkitemId" type="hidden" value="<%= bean.getPropLong("workitemId") %>"/><%}%>
<input name="bizsite_pagetype" type="hidden" value="start">
<input name="_ProcessTemplateName" type="hidden" value='<%=bean.getPropString("ptName")%>'>
<input name="_yahoo_flow_button" type="hidden" value=''>
<!-- Content --> 

    
<!-- Header -->
<table width="100%" cellspacing="0" cellpadding="0" border="0">
<tr>
<td class="ApSegTblInBg">
<table border="0" cellspacing="0" align="center" cellpadding="4" width="100%">
<tr align="center">
<td class="ApSegTitle" style="border-top:0px;"><bizsolo:getLabel type="RESOURCE" name="processTemplateLabel_"></bizsolo:getLabel></td>
</tr></table>
<table border="0" cellspacing="1" align="center" cellpadding="4" width="100%" class="ApSegDataTbl">
<tr border="1" align="center">
<td border="1" width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_INSTANCE_NAME_LABEL"></bizsolo:getLabel></td>
<td border="1" width="55%" class="ApSegGenData"><input name="bizsite_instanceName" size="30" maxlength="240" type="text" class="ApInptTxt"><script>addValue("bizsite_instanceName", "<bizsolo:getLabel type='RESOURCE' name='processTemplateLabel_'/>");</script></td>
<td border="1" width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_PRIORITY_LABEL"></bizsolo:getLabel></td>
<td border="1" width="15%" class="ApSegGenData"><select name="bizsite_priority" id="bizsite_priority" class="ApInptSelect"><c:forEach var="priority" items="${_priorities}"> <option value="${priority}"> <c:choose><c:when test="${priority == 'critical'}"><bizsolo:getLabel type="RESOURCE" name="PRIORITY_CRITICAL"/></c:when><c:when test="${priority == 'high'}"><bizsolo:getLabel type="RESOURCE" name="PRIORITY_HIGH"/></c:when><c:when test="${priority == 'medium'}"><bizsolo:getLabel type="RESOURCE" name="PRIORITY_MEDIUM"/></c:when><c:when test="${priority == 'low'}"><bizsolo:getLabel type="RESOURCE" name="PRIORITY_LOW"/></c:when>    </c:choose>    </option>        </c:forEach>  </select></td>
</tr>
<tr><td border="1" width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_INSTRUCTION_LABEL"></bizsolo:getLabel></td>
<td border="1" colspan="3" class="ApSegGenData"><sbm:message key="workstep.Start.instruction" escapeLine="true"></sbm:message></td></tr>
</table>
</td>
</tr>
</table>

    <table align="left" cellpadding="1" cellspacing="1" class="ApSegDataTbl" id="table1" width="100%">
      <colgroup span="1">
        <col width="100px" span="1">
        <col width="100px" span="1">
      </colgroup>
      <tbody>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField1"><sbm:message key="dataslot.Start.agent_code.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField1" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField2"><sbm:message key="dataslot.Start.attrition_probability.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField2" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField3"><sbm:message key="dataslot.Start.business_category.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField3" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField4"><sbm:message key="dataslot.Start.licence_type.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField4" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField5"><sbm:message key="dataslot.Start.claim_TAT_category.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField5" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField6"><sbm:message key="dataslot.Start.policy_gap.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField6" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField7"><sbm:message key="dataslot.Start.sales_category.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField7" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField8"><sbm:message key="dataslot.Start.claim_per_category.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField8" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField9"><sbm:message key="dataslot.Start.sm_level_vintage.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField9" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField10"><sbm:message key="dataslot.Start.time_last_pol.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField10" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField11"><sbm:message key="dataslot.Start.payout_TAT_category.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="payout_TAT_category" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField12"><sbm:message key="dataslot.Start.vintage_month.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="vintage_month" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField13"><sbm:message key="dataslot.Start.fresh_per.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="fresh_per" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField14"><sbm:message key="dataslot.Start.sm_status.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="sm_status" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField15"><sbm:message key="dataslot.Start.business_last_12month.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="business_last_12month" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField16"><sbm:message key="dataslot.Start.attrition_risk.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="attrition_risk" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">Branch_code</td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="branch_code" args="{'type':'text', 'size':20, 'maxlength':20, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">Branch_name</td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="branch_name" args="{'type':'text', 'size':20, 'maxlength':20, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">SM_Code</td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField12" args="{'type':'text', 'size':20, 'maxlength':20, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">SM_Name</td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField13" args="{'type':'text', 'size':20, 'maxlength':20, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">Role</td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField11" args="{'type':'text', 'size':20, 'maxlength':20, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
      </tbody>
    </table>
    

</div>
<!-- Footer -->

<div id="cmdDiv" style="height:46px;">
<table width="100%" height="100%" cellpadding="0" align="center" cellspacing="0" border="0">
<tr align="center">
<td class="ApButtonDarkBg" width="63%">
<table border="0" cellspacing="0" cellpadding="0">
<tr>
<td class="ApBtnSpace">
<form:button id="bizsite_completeTask" name="bizsite_completeTask" link="CREATE_LABEL" resourceType="RESOURCE"/> </td>
<td class="ApBtnSpace">
<form:button id="bizsite_reset" name="bizsite_reset" link="RESET_LABEL" onclick="sbm.utils.reset" resourceType="RESOURCE"/> </td>
<td class="ApBtnSpace">
<form:button id="btn-cancel" name="btn-cancel" link="CANCEL_LABEL" onclick="sbm.utils.cancel" resourceType="RESOURCE"/> </td>
</tr>
</table>
</td>
</tr>
</table>
</div>

  
                    <div id="resizablepanel" style="display:none">
                        <div class="hd">Alert Dialog</div>
                        <div class="bd"></div>
                        <div class="ft"></div>
                    </div> 
<div id="southDiv" style="height:0px;display:none;"></div></form>
</body>

<script language="JavaScript">
<!--
function beforeInitControls() {
}
-->
</script>
<script language="JavaScript">
<!--
function userValidationJavascript() {
return true;
}
-->
</script>
<sbm:dataSources appName="AgentRetentionProcess" appType="bizlogic">
</sbm:dataSources>
<script language="JavaScript">
<!---->
</script>
<!--Initialize extensible widgets.-->
<script language="JavaScript">
<!--
var _dateFormats = {date:'<%=bean.getPropString(PublicResources.JS_CALENDAR_DATE_FORMAT)%>', dateOnly:'<%=bean.getPropString(PublicResources.JS_CALENDAR_DATE_ONLY_FORMAT)%>'};

var allWidgets = [{widget:'textField1', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'agent_code', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'agent_code', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField2', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'attrition_probability', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'attrition_probability', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField3', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'business_category', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'business_category', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField4', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'licence_type', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'licence_type', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField5', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'claim_TAT_category', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'claim_TAT_category', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField6', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'policy_gap', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'policy_gap', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField7', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'sales_category', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'sales_category', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField8', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'claim_per_category', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'claim_per_category', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField9', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'sm_level_vintage', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'sm_level_vintage', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField10', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'time_last_pol', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'time_last_pol', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'payout_TAT_category', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'payout_TAT_category', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'payout_TAT_category', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'vintage_month', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'vintage_month', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'vintage_month', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'fresh_per', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'fresh_per', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'fresh_per', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'sm_status', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'sm_status', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'sm_status', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'business_last_12month', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'business_last_12month', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'business_last_12month', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'attrition_risk', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'attrition_risk', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'attrition_risk', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'branch_code', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'branch_code', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'branch_code', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'branch_name', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'branch_name', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'branch_name', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField12', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'sm_code', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'sm_code', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField13', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'sm_name', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'sm_name', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField11', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'role', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'role', dataSlotType:'STRING'}, dsType:'STRING', service:'false'}
];
var businessObjects = [];
var formWidgetHandler;
  var def_priority='<%=com.savvion.sbm.util.PriorityHelper.self().getDefaultPriorityAsString()%>';
sbm.utils.onDOMReady = function() {
YAHOO.util.Event.onDOMReady(function(){
  sbm.utils.setPriority('bizsite_priority','<%=com.savvion.sbm.util.PriorityHelper.self().getDefaultPriorityAsString()%>');formWidgetHandler = new FormWidgetHandler(allWidgets,null,{processName:'AgentRetentionProcess',processType:'bizlogic',maxMultiLineLength:${maxMultiLineLength},adapletCache:{'user':''}},'<%=request.getParameter(BizSoloRequest.BSS_FIID)%>');
 });
 }
Ext.onReady(function(){
 var task = new Ext.util.DelayedTask(function(){
});
  task.delay(500);
  var viewport = new Bm.util.BmViewport('',{resultComponentXtype:'container'});

});

   
    scrollToErrors = function() {
        var errorsDiv = document.getElementById('errors');
        if(errorsDiv !== null) {
            errorsDiv.scrollIntoView();
        }
    }
    sbm.utils.onFormSubmit = function() {
        if(!formWidgetHandler.validateWidgets()) {
            scrollToErrors();
            return false;
        }
        try{
            if(!userValidationJavascript()) {
                scrollToErrors();
                return false;
            }              
            sbm.utils.handleFormSubmit();
        }catch(e){
            scrollToErrors();
            return false;
        }

                            document.form.action='<%=response.encodeURL("Start.jsp")%>';
         if(allWidgets.length > 0)formWidgetHandler.saveDataSlots();
         return true;
}
-->
</script>

</html>