<%--  This JSP has been generated by using from xsl version 9.0 at Wed Mar 09 17:54:44 IST 2022 --%>
<!DOCTYPE html>
<html xmlns:sbm="http://www.savvion.com/sbm" xmlns:bizsolo="http://www.savvion.com/sbm/BizSolo" xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:xalan="http://xml.apache.org/xalan" xmlns:fn="http://www.w3.org/2005/02/xpath-functions" xmlns:sfe="http://www.savvion.com/sbm/sfe" xmlns:c="http://java.sun.com/jsp/jstl/core">
<head><META http-equiv="Content-Type" content="text/html; charset=utf-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge">

<%@ page contentType="text/html; charset=UTF-8" %>
<%@ page import="com.savvion.BizSolo.Server.*,com.savvion.BizSolo.beans.*,com.savvion.sbm.util.DatabaseMapping,java.util.Vector,java.util.Locale" %>
<%@ page import="com.savvion.sbm.bizsolo.util.session.*,java.net.*" %>
<%@ page errorPage="/BizSolo/common/jsp/expcontroller.jsp" %>
<%@ taglib uri="/BizSolo/common/tlds/bizsolo.tld" prefix="bizsolo" %>
<%@ taglib uri="/bpmportal/tld/bpmportal.tld" prefix="sbm" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib prefix="form" tagdir="/WEB-INF/tags/form"%>
<%@ taglib prefix="sfe" uri="http://jmaki/v1.0/jsp" %>
  <jsp:useBean id="bizManage" class="com.savvion.sbm.bizmanage.api.BizManageBean" scope="session"></jsp:useBean>
  <jsp:useBean id="bean" class="com.savvion.BizSolo.beans.Bean" scope="session"></jsp:useBean>
  <jsp:useBean id="factoryBean" class="com.savvion.BizSolo.beans.EPFactoryBean" scope="session"></jsp:useBean>
  <jsp:useBean id="bizSite" class="com.savvion.sbm.bpmportal.bizsite.api.BizSiteBean" scope="session"></jsp:useBean>
<%! String _PageName = "Marine"; %>
<%! String __webAppName = "RGICL_MotorUW_App"; %>
<% pageContext.setAttribute( "contextPath", request.getContextPath()+"/"); %>
<% pageContext.setAttribute( "maxMultiLineLength", DatabaseMapping.self().getSQLSize(java.lang.String.class));  %>
<%java.util.List<String> priorities = com.savvion.sbm.bpmportal.util.PortalUtil.self().getPriorities();%>
<% pageContext.setAttribute( "_priorities",priorities); %>
<bizsolo:if test='<%=_PageName.equals(request.getParameter("_PageName")) %>'>
    <bizsolo:setDS name=""></bizsolo:setDS>
    <bizsolo:choose>
<bizsolo:when test='<%=request.getParameter("bizsite_reassignTask") !=null %>'>
      <bizsolo:initDS name="performer" param="bizsite_assigneeName" hexval="FALSE"></bizsolo:initDS>
      <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKReassignWI" perfMethod="commit" mode="BizSite" dsi="CREATOR,PRIORITY,PROCESS_INSTANCE_ID,PROCESSNAME,PROCESS_TEMPLATE_NAME,WORKSTEPNAME" dso="AgentCode,ApprovalAuthority,BASCode,branchCode,BSMBlazeRemark,BSMRemarks,CallEndDate,CallStartDate,CallStatus,Channel,CI_UW_Queue,CreatedBy,CUApprover,CUBlazeRemark,CUEndDate,CUGroup,CUHoldDtStr,CURemarks,CUStartDate,CUStatus,gbTPA,HealthProcess,HealthUW,IRPAS_MARINE_SCUW_QUEUE,isTpaUpdated,LOB,MarineQueue,MiscQueue,OpsTeam,PA_UW_Queue,PackageQueue,ProductCode,proposalNumber,QuoteNo,skipCUActivity,skipOPS,SuspendDate,SuspendStatus,TAT,TravelQueue,UWApprover,UWBlazeRemark,UWEndDate,UWGroup,UWHoldDtStr,UWRemarks,UWStartDate,UWStatus,WCQueue,BusinessType,EndorsementQueue"></bizsolo:executeAction>
</bizsolo:when>
<bizsolo:when test='<%=request.getParameter("bizsite_saveTask") !=null %>'>
      <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKUpdateDS" perfMethod="commit" mode="BizSite" dsi="AgentCode,ApprovalAuthority,BASCode,branchCode,BSMBlazeRemark,BSMRemarks,CallEndDate,CallStartDate,CallStatus,Channel,CI_UW_Queue,CreatedBy,CUApprover,CUBlazeRemark,CUEndDate,CUGroup,CUHoldDtStr,CURemarks,CUStartDate,CUStatus,gbTPA,HealthProcess,HealthUW,IRPAS_MARINE_SCUW_QUEUE,isTpaUpdated,LOB,MarineQueue,MiscQueue,OpsTeam,PA_UW_Queue,PackageQueue,ProductCode,proposalNumber,QuoteNo,skipCUActivity,skipOPS,SuspendDate,SuspendStatus,TAT,TravelQueue,UWApprover,UWBlazeRemark,UWEndDate,UWGroup,UWHoldDtStr,UWRemarks,UWStartDate,UWStatus,WCQueue,BusinessType,EndorsementQueue"></bizsolo:executeAction>
</bizsolo:when>
    <bizsolo:otherwise>
      <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKSetDS" perfMethod="commit" mode="BizSite" dsi="AgentCode,ApprovalAuthority,BASCode,branchCode,BSMBlazeRemark,BSMRemarks,CallEndDate,CallStartDate,CallStatus,Channel,CI_UW_Queue,CreatedBy,CUApprover,CUBlazeRemark,CUEndDate,CUGroup,CUHoldDtStr,CURemarks,CUStartDate,CUStatus,gbTPA,HealthProcess,HealthUW,IRPAS_MARINE_SCUW_QUEUE,isTpaUpdated,LOB,MarineQueue,MiscQueue,OpsTeam,PA_UW_Queue,PackageQueue,ProductCode,proposalNumber,QuoteNo,skipCUActivity,skipOPS,SuspendDate,SuspendStatus,TAT,TravelQueue,UWApprover,UWBlazeRemark,UWEndDate,UWGroup,UWHoldDtStr,UWRemarks,UWStartDate,UWStatus,WCQueue,BusinessType,EndorsementQueue" res=""></bizsolo:executeAction>
      </bizsolo:otherwise>
    </bizsolo:choose>
<% /* Workaround, retAddr will disappear in the future */ %>
<% String retAddr = bean.getPropString("returnPage"); %>
<% if(retAddr != null) { %>
<bizsolo:redirectURL page="<%= retAddr %>"/>
<% } %>
</bizsolo:if>
<bizsolo:if test='<%= ! _PageName.equals(request.getParameter("_PageName")) %>'>
    <bizsolo:initApp mode="BizSite" name="RGICL_MotorUW_App"></bizsolo:initApp>
    <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKGetDS" perfMethod="commit" mode="BizSite" dso="AgentCode,ApprovalAuthority,BASCode,branchCode,BSMBlazeRemark,BSMRemarks,CallEndDate,CallStartDate,CallStatus,Channel,CI_UW_Queue,CreatedBy,CREATOR,CUApprover,CUBlazeRemark,CUEndDate,CUGroup,CUHoldDtStr,CURemarks,CUStartDate,CUStatus,gbTPA,HealthProcess,HealthUW,IRPAS_MARINE_SCUW_QUEUE,isTpaUpdated,LOB,MarineQueue,MiscQueue,OpsTeam,PA_UW_Queue,PackageQueue,PRIORITY,PROCESS_INSTANCE_ID,PROCESSNAME,PROCESS_TEMPLATE_NAME,ProductCode,proposalNumber,QuoteNo,skipCUActivity,skipOPS,STARTTIME,SuspendDate,SuspendStatus,TAT,TravelQueue,UWApprover,UWBlazeRemark,UWEndDate,UWGroup,UWHoldDtStr,UWRemarks,UWStartDate,UWStatus,WCQueue,WORKSTEPNAME,BusinessType,EndorsementQueue"></bizsolo:executeAction>
</bizsolo:if>

<title>Marine</title>
<%boolean isStandaloneBS = (bizManage == null || bizManage.getName() == null || "".equals(bizManage.getName()) || bizManage.getLocale() == null);Locale myLocale = (!isStandaloneBS) ? bizManage.getLocale() : request.getLocale();%>
<!-- Javascript -->
<script language="JavaScript"> var getLocalizedString = parent.getLocalizedString; </script>
<form:includes contextPath="${contextPath}"/>
<script language="JavaScript">
     
      var isIFrame = <%= (PublicResources.INTERACTIVE_MODE.equalsIgnoreCase(bean.getPropString(PublicResources.MODE)) || PublicResources.SLAVE_MODE.equalsIgnoreCase(bean.getPropString(PublicResources.MODE))) ? true : false %>;
      

    function getContextPath(){
        return "<%=request.getContextPath()%>";
    }
</script>


<sbm:setLocale value="<%= bizManage.getLocale() %>"></sbm:setLocale>
<% try{ %><sbm:setBundle scope="page" basename="RGICL_MotorUW_App/properties/RGICL_MotorUW_App"></sbm:setBundle><% } catch(Exception e){}%>
<bizsolo:getApplicationResources baseName="RGICL_MotorUW_App/properties/RGICL_MotorUW_App"/></head>
<body class="apbody yui-skin-sam" onLoad="setCheckBoxStyleForIE();hideControls();beforeInitControls();initControls();initTabs();sbm.utils.onDOMReady();">
<form method="post" name="form" onsubmit="return sbm.utils.onFormSubmit();">
<div id="northDiv" style="height:0px;display:none;"><bizsolo:xsrf/></div><% /* Workaround, activityName will disappear in the future */ %>
<% String activityName = bean.getPropString("workitemName"); %>
<div id="resultDiv">
<div style='visibility:hidden;display:none' class='vBoxClass' name='errors' id='errors'></div>
<input name="_PageName" type="hidden" value="Marine">
<%if(bean.getPropString("workitemName") != null) {%><input name="_WorkitemName" type="hidden" value="<%= URLHexCoder.encode(bean.getPropString("workitemName")) %>"/><input name="_WorkitemId" type="hidden" value="<%= bean.getPropLong("workitemId") %>"/><%}%>
<input name="bizsite_pagetype" type="hidden" value="activity">
<input name="_ProcessTemplateName" type="hidden" value='<%=bean.getPropString("ptName")%>'>
<input name="_yahoo_flow_button" type="hidden" value=''>
<!-- Content --> 

    
<!-- Header -->

                    <bizsolo:choose><bizsolo:when test='<%=bean.getPropString(\"workitemName\") != null %>'><table width="100%" cellspacing="0" cellpadding="0" border="0">
<tr>
<td class="ApSegTblInBg">
<table width="100%" cellpadding="4" align="center" cellspacing="0" border="0">
<tr>

<td class="ApSegTitle" align="center"><bizsolo:choose><bizsolo:when test='<%=bean.getPropString(\"workitemName\") != null %>'><bizsolo:getDS name="workitemName"></bizsolo:getDS></bizsolo:when><bizsolo:otherwise><%=_PageName%></bizsolo:otherwise></bizsolo:choose></td>
</tr>
</table>
<table class="ApSegDataTbl" width="100%" cellspacing="1" cellpadding="4" border="0">
<tr>
<td width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_INSTRUCTION_LABEL"></bizsolo:getLabel></td><td width="85%" class="ApSegGenData" colspan="5"><sbm:message key="workstep.Marine.instruction" escapeLine="true"></sbm:message></td>
</tr>
<tr>
<td width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_PRIORITY_LABEL"></bizsolo:getLabel></td><td width="15%" class="ApSegGenData"><bizsolo:getDS name="bizsite_priority"></bizsolo:getDS></td>
<td width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_STARTDATE_LABEL"></bizsolo:getLabel></td><td width="15%" class="ApSegGenData"><bizsolo:getDS name="bizsite_startDate"></bizsolo:getDS></td>
<td width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_DUEDATE_LABEL"></bizsolo:getLabel></td><td width="15%" class="ApSegGenData"><bizsolo:getDS name="bizsite_dueDate"></bizsolo:getDS></td>
</tr>
</table>
</td>
</tr>
</table></bizsolo:when></bizsolo:choose>

    <table align="left" cellpadding="1" cellspacing="1" class="ApSegDataTbl" id="table1" width="100%">
      <colgroup span="1">
        <col width="159px" span="1">
        <col width="100px" span="1">
      </colgroup>
      <tbody>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField1"><sbm:message key="dataslot.Marine.AgentCode.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField1" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField2"><sbm:message key="dataslot.Marine.ApprovalAuthority.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField2" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField3"><sbm:message key="dataslot.Marine.BASCode.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField3" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField4"><sbm:message key="dataslot.Marine.branchCode.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField4" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField5"><sbm:message key="dataslot.Marine.BSMBlazeRemark.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField5" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField6"><sbm:message key="dataslot.Marine.BSMRemarks.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField6" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField7"><sbm:message key="dataslot.Marine.CallEndDate.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField7" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField8"><sbm:message key="dataslot.Marine.CallStartDate.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField8" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField9"><sbm:message key="dataslot.Marine.CallStatus.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField9" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField10"><sbm:message key="dataslot.Marine.Channel.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField10" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField11"><sbm:message key="dataslot.Marine.CI_UW_Queue.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField11" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField12"><sbm:message key="dataslot.Marine.CreatedBy.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField12" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField13"><sbm:message key="dataslot.Marine.CREATOR.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField13" args="{'type':'text', 'size':20, 'maxlength':20, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField14"><sbm:message key="dataslot.Marine.CUApprover.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField14" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField15"><sbm:message key="dataslot.Marine.CUBlazeRemark.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField15" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField16"><sbm:message key="dataslot.Marine.CUEndDate.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField16" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField17"><sbm:message key="dataslot.Marine.CUGroup.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField17" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField18"><sbm:message key="dataslot.Marine.CUHoldDtStr.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField18" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField19"><sbm:message key="dataslot.Marine.CURemarks.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField19" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField20"><sbm:message key="dataslot.Marine.CUStartDate.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField20" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField21"><sbm:message key="dataslot.Marine.CUStatus.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField21" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="checkbox1"><sbm:message key="dataslot.Marine.gbTPA.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.checkbox" id="checkbox1" args="{'layout':'vertical', 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process Checkbox widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField22"><sbm:message key="dataslot.Marine.HealthProcess.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField22" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField23"><sbm:message key="dataslot.Marine.HealthUW.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField23" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField24"><sbm:message key="dataslot.Marine.IRPAS_MARINE_SCUW_QUEUE.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField24" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="checkbox2"><sbm:message key="dataslot.Marine.isTpaUpdated.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.checkbox" id="checkbox2" args="{'layout':'vertical', 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process Checkbox widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField25"><sbm:message key="dataslot.Marine.LOB.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField25" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField26"><sbm:message key="dataslot.Marine.MarineQueue.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField26" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField27"><sbm:message key="dataslot.Marine.MiscQueue.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField27" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField28"><sbm:message key="dataslot.Marine.OpsTeam.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField28" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField29"><sbm:message key="dataslot.Marine.PA_UW_Queue.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField29" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField30"><sbm:message key="dataslot.Marine.PackageQueue.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField30" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField31"><sbm:message key="dataslot.Marine.PRIORITY.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField31" args="{'type':'text', 'size':20, 'maxlength':20, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField32"><sbm:message key="dataslot.Marine.PROCESS_INSTANCE_ID.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField32" args="{'type':'text', 'size':20, 'maxlength':20, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField33"><sbm:message key="dataslot.Marine.PROCESSNAME.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField33" args="{'type':'text', 'size':20, 'maxlength':20, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField34"><sbm:message key="dataslot.Marine.PROCESS_TEMPLATE_NAME.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField34" args="{'type':'text', 'size':20, 'maxlength':20, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField35"><sbm:message key="dataslot.Marine.ProductCode.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField35" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField36"><sbm:message key="dataslot.Marine.proposalNumber.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField36" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField37"><sbm:message key="dataslot.Marine.QuoteNo.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField37" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="checkbox3"><sbm:message key="dataslot.Marine.skipCUActivity.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.checkbox" id="checkbox3" args="{'layout':'vertical', 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process Checkbox widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField38"><sbm:message key="dataslot.Marine.skipOPS.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField38" args="{'type':'text', 'size':20, 'maxlength':10, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField39"><sbm:message key="dataslot.Marine.STARTTIME.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField39" args="{'type':'text', 'size':20, 'maxlength':20, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField40"><sbm:message key="dataslot.Marine.SuspendDate.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField40" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField41"><sbm:message key="dataslot.Marine.SuspendStatus.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField41" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField42"><sbm:message key="dataslot.Marine.TAT.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField42" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField43"><sbm:message key="dataslot.Marine.TravelQueue.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField43" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField44"><sbm:message key="dataslot.Marine.UWApprover.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField44" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField45"><sbm:message key="dataslot.Marine.UWBlazeRemark.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField45" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField46"><sbm:message key="dataslot.Marine.UWEndDate.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField46" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField47"><sbm:message key="dataslot.Marine.UWGroup.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField47" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField48"><sbm:message key="dataslot.Marine.UWHoldDtStr.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField48" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField49"><sbm:message key="dataslot.Marine.UWRemarks.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField49" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField50"><sbm:message key="dataslot.Marine.UWStartDate.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField50" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField51"><sbm:message key="dataslot.Marine.UWStatus.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField51" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField52"><sbm:message key="dataslot.Marine.WCQueue.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField52" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField53"><sbm:message key="dataslot.Marine.WORKSTEPNAME.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField53" args="{'type':'text', 'size':20, 'maxlength':20, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField54"><sbm:message key="dataslot.Marine.BusinessType.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField54" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="ApSegDataslotLabel" id="" for="textField55"><sbm:message key="dataslot.Marine.EndorsementQueue.label"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField55" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Aurea Process textfield widget', 'tabOrder':'0'}" />

          </td>
        </tr>
      </tbody>
    </table>
    

</div>
<!-- Footer -->

<div id="cmdDiv" style="height:46px;">
<table width="100%" height="100%" cellpadding="0" align="center" cellspacing="0" border="0">
<tr align="center">
<td class="ApButtonDarkBg" width="63%">
<table border="0" cellspacing="0" cellpadding="0">
<tr>
<td class="ApBtnSpace">
<bizsolo:isNotSuspended><form:button id="bizsite_completeTask" name="bizsite_completeTask" link="COMPLETE_LABEL" resourceType="RESOURCE"/> </bizsolo:isNotSuspended></td>
<td class="ApBtnSpace">
<form:button id="bizsite_saveTask" name="bizsite_saveTask" link="SAVE_LABEL" resourceType="RESOURCE"/> </td>
<bizsolo:isAssigned></bizsolo:isAssigned><td class="ApBtnSpace">
<form:button id="bizsite_reset" name="bizsite_reset" link="RESET_LABEL" onclick="sbm.utils.reset" resourceType="RESOURCE"/> </td>
<td class="ApBtnSpace">
<form:button id="btn-cancel" name="btn-cancel" link="CANCEL_LABEL" onclick="sbm.utils.cancel" resourceType="RESOURCE"/> </td>
<bizsolo:isAssigned><td class="ApBtnSpace"><input class="ApInptTxt" type="text" name="bizsite_assigneeName" size="20"></td><td class="ApBtnSpace"><a href="javascript://" onClick="setUserControl(document.form.bizsite_assigneeName);searchUser()"><img width="16" height="16" border="0" title="Search" src="<c:out value='${contextPath}'/>bpmportal/css/app<%= bizManage.getTheme() %>/images/icon_edit_user_search_single.gif"></img></a></td><td class="ApBtnSpace"><form:button id="bizsite_reassignTask" name="bizsite_reassignTask" link="REASSIGN_LABEL" resourceType="RESOURCE"/> </td>
</bizsolo:isAssigned></tr>
</table>
</td>
</tr>
</table>
</div>

  
                    <div id="resizablepanel" style="display:none">
                        <div class="hd">Alert Dialog</div>
                        <div class="bd"></div>
                        <div class="ft"></div>
                    </div> 
<div id="southDiv" style="height:0px;display:none;"></div></form>
</body>

<script language="JavaScript">
<!--
function beforeInitControls() {
}
-->
</script>
<script language="JavaScript">
<!--
function userValidationJavascript() {
return true;
}
-->
</script>
<sbm:dataSources appName="RGICL_MotorUW_App" appType="bizlogic">
</sbm:dataSources>
<script language="JavaScript">
<!---->
</script>
<!--Initialize extensible widgets.-->
<script language="JavaScript">
<!--
var _dateFormats = {date:'<%=bean.getPropString(PublicResources.JS_CALENDAR_DATE_FORMAT)%>', dateOnly:'<%=bean.getPropString(PublicResources.JS_CALENDAR_DATE_ONLY_FORMAT)%>'};

var allWidgets = [{widget:'textField1', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'AgentCode', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'AgentCode', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField2', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'ApprovalAuthority', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'ApprovalAuthority', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField3', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'BASCode', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'BASCode', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField4', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'branchCode', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'branchCode', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField5', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'BSMBlazeRemark', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'BSMBlazeRemark', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField6', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'BSMRemarks', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'BSMRemarks', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField7', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CallEndDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CallEndDate', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField8', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CallStartDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CallStartDate', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField9', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CallStatus', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CallStatus', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField10', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'Channel', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'Channel', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField11', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CI_UW_Queue', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CI_UW_Queue', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField12', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CreatedBy', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CreatedBy', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField13', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CREATOR', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'', dataSlotType:''}, dsType:'', service:'false'},
{widget:'textField14', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CUApprover', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CUApprover', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField15', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CUBlazeRemark', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CUBlazeRemark', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField16', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CUEndDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CUEndDate', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField17', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CUGroup', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CUGroup', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField18', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CUHoldDtStr', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CUHoldDtStr', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField19', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CURemarks', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CURemarks', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField20', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CUStartDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CUStartDate', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField21', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CUStatus', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CUStatus', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'checkbox1', bound:'true', editable:'true', type:'sbm.checkbox', source: {type:'DATASLOT', dataSlotName:'gbTPA', dataSlotType:'BOOLEAN'}, target:{type:'DATASLOT', dataSlotName:'gbTPA', dataSlotType:'BOOLEAN'}, dsType:'', service:'false'},
{widget:'textField22', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'HealthProcess', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'HealthProcess', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField23', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'HealthUW', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'HealthUW', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField24', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'IRPAS_MARINE_SCUW_QUEUE', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'IRPAS_MARINE_SCUW_QUEUE', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'checkbox2', bound:'true', editable:'true', type:'sbm.checkbox', source: {type:'DATASLOT', dataSlotName:'isTpaUpdated', dataSlotType:'BOOLEAN'}, target:{type:'DATASLOT', dataSlotName:'isTpaUpdated', dataSlotType:'BOOLEAN'}, dsType:'', service:'false'},
{widget:'textField25', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'LOB', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'LOB', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField26', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'MarineQueue', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'MarineQueue', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField27', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'MiscQueue', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'MiscQueue', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField28', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'OpsTeam', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'OpsTeam', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField29', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'PA_UW_Queue', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'PA_UW_Queue', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField30', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'PackageQueue', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'PackageQueue', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField31', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'PRIORITY', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'', dataSlotType:''}, dsType:'', service:'false'},
{widget:'textField32', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'PROCESS_INSTANCE_ID', dataSlotType:'LONG'}, target:{type:'DATASLOT', dataSlotName:'', dataSlotType:''}, dsType:'', service:'false'},
{widget:'textField33', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'PROCESSNAME', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'', dataSlotType:''}, dsType:'', service:'false'},
{widget:'textField34', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'PROCESS_TEMPLATE_NAME', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'', dataSlotType:''}, dsType:'', service:'false'},
{widget:'textField35', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'ProductCode', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'ProductCode', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField36', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'proposalNumber', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'proposalNumber', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField37', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'QuoteNo', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'QuoteNo', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'checkbox3', bound:'true', editable:'true', type:'sbm.checkbox', source: {type:'DATASLOT', dataSlotName:'skipCUActivity', dataSlotType:'BOOLEAN'}, target:{type:'DATASLOT', dataSlotName:'skipCUActivity', dataSlotType:'BOOLEAN'}, dsType:'', service:'false'},
{widget:'textField38', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'skipOPS', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'skipOPS', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField39', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'STARTTIME', dataSlotType:'LONG'}, target:{type:'DATASLOT', dataSlotName:'', dataSlotType:''}, dsType:'', service:'false'},
{widget:'textField40', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'SuspendDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'SuspendDate', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField41', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'SuspendStatus', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'SuspendStatus', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField42', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'TAT', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'TAT', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField43', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'TravelQueue', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'TravelQueue', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField44', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWApprover', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWApprover', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField45', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWBlazeRemark', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWBlazeRemark', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField46', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWEndDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWEndDate', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField47', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWGroup', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWGroup', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField48', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWHoldDtStr', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWHoldDtStr', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField49', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWRemarks', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWRemarks', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField50', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWStartDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWStartDate', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField51', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWStatus', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWStatus', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField52', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'WCQueue', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'WCQueue', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField53', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'WORKSTEPNAME', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'', dataSlotType:''}, dsType:'', service:'false'},
{widget:'textField54', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'BusinessType', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'BusinessType', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField55', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'EndorsementQueue', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'EndorsementQueue', dataSlotType:'STRING'}, dsType:'', service:'false'}
];
var businessObjects = [];
var formWidgetHandler;

sbm.utils.onDOMReady = function() {
YAHOO.util.Event.onDOMReady(function(){
formWidgetHandler = new FormWidgetHandler(allWidgets,null,{processName:'RGICL_MotorUW_App',processType:'bizlogic',maxMultiLineLength:${maxMultiLineLength},adapletCache:{}},'<%=request.getParameter(BizSoloRequest.BSS_FIID)%>');
 });
 }
Ext.onReady(function(){
 var task = new Ext.util.DelayedTask(function(){
});
  task.delay(500);
  var viewport = new Bm.util.BmViewport('',{resultComponentXtype:'container'});

});

   
    scrollToErrors = function() {
        var errorsDiv = document.getElementById('errors');
        if(errorsDiv !== null) {
            errorsDiv.scrollIntoView();
        }
    }
    sbm.utils.onFormSubmit = function() {
        if(!formWidgetHandler.validateWidgets()) {
            scrollToErrors();
            return false;
        }
        try{
            if(!userValidationJavascript()) {
                scrollToErrors();
                return false;
            }              
            sbm.utils.handleFormSubmit();
        }catch(e){
            scrollToErrors();
            return false;
        }

                            document.form.action='<%=response.encodeURL("Marine.jsp")%>';
         if(allWidgets.length > 0)formWidgetHandler.saveDataSlots();
         return true;
}
-->
</script>

</html>