<%--  This JSP has been generated by using from xsl version 9.0 at Wed Mar 09 17:54:42 IST 2022 --%>
<!DOCTYPE html>
<html xmlns:sbm="http://www.savvion.com/sbm" xmlns:bizsolo="http://www.savvion.com/sbm/BizSolo" xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:xalan="http://xml.apache.org/xalan" xmlns:fn="http://www.w3.org/2005/02/xpath-functions" xmlns:sfe="http://www.savvion.com/sbm/sfe" xmlns:c="http://java.sun.com/jsp/jstl/core">
<head><META http-equiv="Content-Type" content="text/html; charset=utf-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge">

<%@ page contentType="text/html; charset=UTF-8" %>
<%@ page import="com.savvion.BizSolo.Server.*,com.savvion.BizSolo.beans.*,com.savvion.sbm.util.DatabaseMapping,java.util.Vector,java.util.Locale" %>
<%@ page import="com.savvion.sbm.bizsolo.util.session.*,java.net.*" %>
<%@ page errorPage="/BizSolo/common/jsp/expcontroller.jsp" %>
<%@ taglib uri="/BizSolo/common/tlds/bizsolo.tld" prefix="bizsolo" %>
<%@ taglib uri="/bpmportal/tld/bpmportal.tld" prefix="sbm" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib prefix="form" tagdir="/WEB-INF/tags/form"%>
<%@ taglib prefix="sfe" uri="http://jmaki/v1.0/jsp" %>
  <jsp:useBean id="bizManage" class="com.savvion.sbm.bizmanage.api.BizManageBean" scope="session"></jsp:useBean>
  <jsp:useBean id="bean" class="com.savvion.BizSolo.beans.Bean" scope="session"></jsp:useBean>
  <jsp:useBean id="factoryBean" class="com.savvion.BizSolo.beans.EPFactoryBean" scope="session"></jsp:useBean>
  <jsp:useBean id="bizSite" class="com.savvion.sbm.bpmportal.bizsite.api.BizSiteBean" scope="session"></jsp:useBean>
<%! String _PageName = "WC_ACTIVITY"; %>
<%! String __webAppName = "RGICL_MotorUW_App"; %>
<% pageContext.setAttribute( "contextPath", request.getContextPath()+"/"); %>
<% pageContext.setAttribute( "maxMultiLineLength", DatabaseMapping.self().getSQLSize(java.lang.String.class));  %>
<%java.util.List<String> priorities = com.savvion.sbm.bpmportal.util.PortalUtil.self().getPriorities();%>
<% pageContext.setAttribute( "_priorities",priorities); %>
<bizsolo:if test='<%=_PageName.equals(request.getParameter("_PageName")) %>'>
    <bizsolo:setDS name="AgentCode,ApprovalAuthority,BASCode,branchCode,BSMBlazeRemark,BSMRemarks,CallEndDate,CallStartDate,CallStatus,Channel,CI_UW_Queue,CreatedBy,CUApprover,CUBlazeRemark,CUEndDate,CUGroup,CUHoldDtStr,CURemarks,CUStartDate,CUStatus,gbTPA,HealthProcess,HealthUW,isTpaUpdated,LOB,MiscQueue,OpsTeam,PA_UW_Queue,PackageQueue,ProductCode,proposalNumber,QuoteNo,skipCUActivity,skipOPS,SuspendDate,SuspendStatus,TAT,TravelQueue,UWApprover,UWBlazeRemark,UWEndDate,UWGroup,UWHoldDtStr,UWRemarks,UWStartDate,UWStatus,WCQueue,BusinessType"></bizsolo:setDS>
    <bizsolo:choose>
<bizsolo:when test='<%=request.getParameter("bizsite_reassignTask") !=null %>'>
      <bizsolo:initDS name="performer" param="bizsite_assigneeName" hexval="FALSE"></bizsolo:initDS>
      <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKReassignWI" perfMethod="commit" mode="BizSite" dsi="" dso="BusinessType,WCQueue,UWStatus,UWStartDate,UWRemarks,UWHoldDtStr,UWGroup,UWEndDate,UWBlazeRemark,UWApprover,TravelQueue,TAT,SuspendStatus,SuspendDate,skipOPS,skipCUActivity,QuoteNo,proposalNumber,ProductCode,PackageQueue,PA_UW_Queue,OpsTeam,MiscQueue,LOB,isTpaUpdated,HealthUW,HealthProcess,gbTPA,CUStatus,CUStartDate,CURemarks,CUHoldDtStr,CUGroup,CUEndDate,CUBlazeRemark,CUApprover,CreatedBy,CI_UW_Queue,Channel,CallStatus,CallStartDate,CallEndDate,BSMRemarks,BSMBlazeRemark,branchCode,BASCode,ApprovalAuthority,AgentCode"></bizsolo:executeAction>
</bizsolo:when>
<bizsolo:when test='<%=request.getParameter("bizsite_saveTask") !=null %>'>
      <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKUpdateDS" perfMethod="commit" mode="BizSite" dsi="BusinessType,WCQueue,UWStatus,UWStartDate,UWRemarks,UWHoldDtStr,UWGroup,UWEndDate,UWBlazeRemark,UWApprover,TravelQueue,TAT,SuspendStatus,SuspendDate,skipOPS,skipCUActivity,QuoteNo,proposalNumber,ProductCode,PackageQueue,PA_UW_Queue,OpsTeam,MiscQueue,LOB,isTpaUpdated,HealthUW,HealthProcess,gbTPA,CUStatus,CUStartDate,CURemarks,CUHoldDtStr,CUGroup,CUEndDate,CUBlazeRemark,CUApprover,CreatedBy,CI_UW_Queue,Channel,CallStatus,CallStartDate,CallEndDate,BSMRemarks,BSMBlazeRemark,branchCode,BASCode,ApprovalAuthority,AgentCode"></bizsolo:executeAction>
</bizsolo:when>
    <bizsolo:otherwise>
      <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKSetDS" perfMethod="commit" mode="BizSite" dsi="BusinessType,WCQueue,UWStatus,UWStartDate,UWRemarks,UWHoldDtStr,UWGroup,UWEndDate,UWBlazeRemark,UWApprover,TravelQueue,TAT,SuspendStatus,SuspendDate,skipOPS,skipCUActivity,QuoteNo,proposalNumber,ProductCode,PackageQueue,PA_UW_Queue,OpsTeam,MiscQueue,LOB,isTpaUpdated,HealthUW,HealthProcess,gbTPA,CUStatus,CUStartDate,CURemarks,CUHoldDtStr,CUGroup,CUEndDate,CUBlazeRemark,CUApprover,CreatedBy,CI_UW_Queue,Channel,CallStatus,CallStartDate,CallEndDate,BSMRemarks,BSMBlazeRemark,branchCode,BASCode,ApprovalAuthority,AgentCode" res=""></bizsolo:executeAction>
      </bizsolo:otherwise>
    </bizsolo:choose>
<% /* Workaround, retAddr will disappear in the future */ %>
<% String retAddr = bean.getPropString("returnPage"); %>
<% if(retAddr != null) { %>
<bizsolo:redirectURL page="<%= retAddr %>"/>
<% } %>
</bizsolo:if>
<bizsolo:if test='<%= ! _PageName.equals(request.getParameter("_PageName")) %>'>
    <bizsolo:initApp mode="BizSite" name="RGICL_MotorUW_App"></bizsolo:initApp>
<bizsolo:initDS name="AgentCode" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="ApprovalAuthority" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="BASCode" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="branchCode" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="BSMBlazeRemark" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="BSMRemarks" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="CallEndDate" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="CallStartDate" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="CallStatus" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="Channel" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="CI_UW_Queue" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="CreatedBy" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="CUApprover" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="CUBlazeRemark" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="CUEndDate" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="CUGroup" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="CUHoldDtStr" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="CURemarks" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="CUStartDate" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="CUStatus" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="gbTPA" type="BOOLEAN"></bizsolo:initDS>
<bizsolo:initDS name="HealthProcess" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="HealthUW" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="isTpaUpdated" type="BOOLEAN"></bizsolo:initDS>
<bizsolo:initDS name="LOB" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="MiscQueue" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="OpsTeam" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="PA_UW_Queue" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="PackageQueue" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="ProductCode" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="proposalNumber" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="QuoteNo" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="skipCUActivity" type="BOOLEAN"></bizsolo:initDS>
<bizsolo:initDS name="skipOPS" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="SuspendDate" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="SuspendStatus" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="TAT" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="TravelQueue" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="UWApprover" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="UWBlazeRemark" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="UWEndDate" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="UWGroup" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="UWHoldDtStr" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="UWRemarks" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="UWStartDate" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="UWStatus" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="WCQueue" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="BusinessType" type="STRING"></bizsolo:initDS>
    <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKGetDS" perfMethod="commit" mode="BizSite" dso="BusinessType,WCQueue,UWStatus,UWStartDate,UWRemarks,UWHoldDtStr,UWGroup,UWEndDate,UWBlazeRemark,UWApprover,TravelQueue,TAT,SuspendStatus,SuspendDate,skipOPS,skipCUActivity,QuoteNo,proposalNumber,ProductCode,PackageQueue,PA_UW_Queue,OpsTeam,MiscQueue,LOB,isTpaUpdated,HealthUW,HealthProcess,gbTPA,CUStatus,CUStartDate,CURemarks,CUHoldDtStr,CUGroup,CUEndDate,CUBlazeRemark,CUApprover,CreatedBy,CI_UW_Queue,Channel,CallStatus,CallStartDate,CallEndDate,BSMRemarks,BSMBlazeRemark,branchCode,BASCode,ApprovalAuthority,AgentCode"></bizsolo:executeAction>
</bizsolo:if>

<title>WC_ACTIVITY</title>
<%boolean isStandaloneBS = (bizManage == null || bizManage.getName() == null || "".equals(bizManage.getName()) || bizManage.getLocale() == null);Locale myLocale = (!isStandaloneBS) ? bizManage.getLocale() : request.getLocale();%>
<!-- Javascript -->
<script language="JavaScript"> var getLocalizedString = parent.getLocalizedString; </script>
<form:includes contextPath="${contextPath}"/>
<script language="JavaScript">
     
      var isIFrame = <%= (PublicResources.INTERACTIVE_MODE.equalsIgnoreCase(bean.getPropString(PublicResources.MODE)) || PublicResources.SLAVE_MODE.equalsIgnoreCase(bean.getPropString(PublicResources.MODE))) ? true : false %>;
      

    function getContextPath(){
        return "<%=request.getContextPath()%>";
    }
</script>


<sbm:setLocale value="<%= bizManage.getLocale() %>"></sbm:setLocale>
<% try{ %><sbm:setBundle scope="page" basename="RGICL_MotorUW_App/properties/RGICL_MotorUW_App"></sbm:setBundle><% } catch(Exception e){}%>
<bizsolo:getApplicationResources baseName="RGICL_MotorUW_App/properties/RGICL_MotorUW_App"/></head>
<body class="apbody yui-skin-sam" onLoad="setCheckBoxStyleForIE();hideControls();beforeInitControls();initControls();initTabs();sbm.utils.onDOMReady();">
<form method="post" name="form" onsubmit="return sbm.utils.onFormSubmit();">
<div id="northDiv" style="height:0px;display:none;"><bizsolo:xsrf/></div><% /* Workaround, activityName will disappear in the future */ %>
<% String activityName = bean.getPropString("workitemName"); %>
<div id="resultDiv">
<div style='visibility:hidden;display:none' class='vBoxClass' name='errors' id='errors'></div>
<input name="_PageName" type="hidden" value="WC_ACTIVITY">
<%if(bean.getPropString("workitemName") != null) {%><input name="_WorkitemName" type="hidden" value="<%= URLHexCoder.encode(bean.getPropString("workitemName")) %>"/><input name="_WorkitemId" type="hidden" value="<%= bean.getPropLong("workitemId") %>"/><%}%>
<input name="bizsite_pagetype" type="hidden" value="activity">
<input name="_ProcessTemplateName" type="hidden" value='<%=bean.getPropString("ptName")%>'>
<input name="_yahoo_flow_button" type="hidden" value=''>
<!-- Content --> 

    
<!-- Header -->

                    <bizsolo:choose><bizsolo:when test='<%=bean.getPropString(\"workitemName\") != null %>'><table width="100%" cellspacing="0" cellpadding="0" border="0">
<tr>
<td class="ApSegTblInBg">
<table width="100%" cellpadding="4" align="center" cellspacing="0" border="0">
<tr>

<td class="ApSegTitle" align="center"><bizsolo:choose><bizsolo:when test='<%=bean.getPropString(\"workitemName\") != null %>'><bizsolo:getDS name="workitemName"></bizsolo:getDS></bizsolo:when><bizsolo:otherwise><%=_PageName%></bizsolo:otherwise></bizsolo:choose></td>
</tr>
</table>
<table class="ApSegDataTbl" width="100%" cellspacing="1" cellpadding="4" border="0">
<tr>
<td width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_INSTRUCTION_LABEL"></bizsolo:getLabel></td><td width="85%" class="ApSegGenData" colspan="5"><sbm:message key="workstep.WC_ACTIVITY.instruction" escapeLine="true"></sbm:message></td>
</tr>
<tr>
<td width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_PRIORITY_LABEL"></bizsolo:getLabel></td><td width="15%" class="ApSegGenData"><bizsolo:getDS name="bizsite_priority"></bizsolo:getDS></td>
<td width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_STARTDATE_LABEL"></bizsolo:getLabel></td><td width="15%" class="ApSegGenData"><bizsolo:getDS name="bizsite_startDate"></bizsolo:getDS></td>
<td width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_DUEDATE_LABEL"></bizsolo:getLabel></td><td width="15%" class="ApSegGenData"><bizsolo:getDS name="bizsite_dueDate"></bizsolo:getDS></td>
</tr>
</table>
</td>
</tr>
</table></bizsolo:when></bizsolo:choose>

    <table align="left" cellpadding="0" cellspacing="0" class="ApSegDataTbl" id="table1" width="100%">
      <colgroup span="1">
        <col span="1">
        <col span="1">
      </colgroup>
      <tbody>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField1"><sbm:message key="AgentCode"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField1" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField2"><sbm:message key="ApprovalAuthority"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField2" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField3"><sbm:message key="BASCode"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField3" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField4"><sbm:message key="branchCode"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField4" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField5"><sbm:message key="BSMBlazeRemark"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField5" args="{'type':'text', 'size':20, 'maxlength':2000, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField6"><sbm:message key="BSMRemarks"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField6" args="{'type':'text', 'size':20, 'maxlength':2000, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField7"><sbm:message key="CallEndDate"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField7" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField8"><sbm:message key="CallStartDate"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField8" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField9"><sbm:message key="CallStatus"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField9" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField10"><sbm:message key="Channel"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField10" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField11"><sbm:message key="CI_UW_Queue"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField11" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField12"><sbm:message key="CreatedBy"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField12" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField13"><sbm:message key="CUApprover"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField13" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField14"><sbm:message key="CUBlazeRemark"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField14" args="{'type':'text', 'size':20, 'maxlength':2000, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField15"><sbm:message key="CUEndDate"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField15" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField16"><sbm:message key="CUGroup"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField16" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField17"><sbm:message key="CUHoldDtStr"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField17" args="{'type':'text', 'size':20, 'maxlength':500, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField18"><sbm:message key="CURemarks"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField18" args="{'type':'text', 'size':20, 'maxlength':2000, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField19"><sbm:message key="CUStartDate"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField19" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField20"><sbm:message key="CUStatus"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField20" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="checkBox1"><sbm:message key="gbTPA"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.checkbox" id="checkBox1" args="{'layout':'vertical', 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField21"><sbm:message key="HealthProcess"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField21" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField22"><sbm:message key="HealthUW"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField22" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="checkBox2"><sbm:message key="isTpaUpdated"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.checkbox" id="checkBox2" args="{'layout':'vertical', 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField23"><sbm:message key="LOB"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField23" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField24"><sbm:message key="MiscQueue"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField24" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField25"><sbm:message key="OpsTeam"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField25" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField26"><sbm:message key="PA_UW_Queue"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField26" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField27"><sbm:message key="PackageQueue"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField27" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField28"><sbm:message key="ProductCode"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField28" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField29"><sbm:message key="proposalNumber"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField29" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField30"><sbm:message key="QuoteNo"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField30" args="{'type':'text', 'size':20, 'maxlength':64, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="checkBox3"><sbm:message key="skipCUActivity"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.checkbox" id="checkBox3" args="{'layout':'vertical', 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField31"><sbm:message key="skipOPS"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField31" args="{'type':'text', 'size':20, 'maxlength':10, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField32"><sbm:message key="SuspendDate"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField32" args="{'type':'text', 'size':20, 'maxlength':2000, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField33"><sbm:message key="SuspendStatus"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField33" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField34"><sbm:message key="TAT"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField34" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField35"><sbm:message key="TravelQueue"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField35" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField36"><sbm:message key="UWApprover"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField36" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField37"><sbm:message key="UWBlazeRemark"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField37" args="{'type':'text', 'size':20, 'maxlength':2000, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField38"><sbm:message key="UWEndDate"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField38" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField39"><sbm:message key="UWGroup"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField39" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField40"><sbm:message key="UWHoldDtStr"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField40" args="{'type':'text', 'size':20, 'maxlength':500, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField41"><sbm:message key="UWRemarks"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField41" args="{'type':'text', 'size':20, 'maxlength':2000, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField42"><sbm:message key="UWStartDate"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField42" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField43"><sbm:message key="UWStatus"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField43" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegGenLabel" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <Label class="" id="" for="textField44"><sbm:message key="WCQueue"></sbm:message></Label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField44" args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
      </tbody>
    </table>
    <Label class="ApSegDataslotLabel" id="" for="textField45"><sbm:message key="dataslot.WC_ACTIVITY.BusinessType.label"></sbm:message></Label>
    <sfe:widget name="sbm.textfield" id="textField45" args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'Savvion textfield widget', 'tabOrder':'0'}" />

    <br clear="all">
<br clear="all">


</div>
<!-- Footer -->

<div id="cmdDiv" style="height:46px;">
<table width="100%" height="100%" cellpadding="0" align="center" cellspacing="0" border="0">
<tr align="center">
<td class="ApButtonDarkBg" width="63%">
<table border="0" cellspacing="0" cellpadding="0">
<tr>
<td class="ApBtnSpace">
<bizsolo:isNotSuspended><form:button id="bizsite_completeTask" name="bizsite_completeTask" link="COMPLETE_LABEL" resourceType="RESOURCE"/> </bizsolo:isNotSuspended></td>
<td class="ApBtnSpace">
<form:button id="bizsite_saveTask" name="bizsite_saveTask" link="SAVE_LABEL" resourceType="RESOURCE"/> </td>
<bizsolo:isAssigned></bizsolo:isAssigned><td class="ApBtnSpace">
<form:button id="bizsite_reset" name="bizsite_reset" link="RESET_LABEL" onclick="sbm.utils.reset" resourceType="RESOURCE"/> </td>
<td class="ApBtnSpace">
<form:button id="btn-cancel" name="btn-cancel" link="CANCEL_LABEL" onclick="sbm.utils.cancel" resourceType="RESOURCE"/> </td>
<bizsolo:isAssigned><td class="ApBtnSpace"><input class="ApInptTxt" type="text" name="bizsite_assigneeName" size="20"></td><td class="ApBtnSpace"><a href="javascript://" onClick="setUserControl(document.form.bizsite_assigneeName);searchUser()"><img width="16" height="16" border="0" title="Search" src="<c:out value='${contextPath}'/>bpmportal/css/app<%= bizManage.getTheme() %>/images/icon_edit_user_search_single.gif"></img></a></td><td class="ApBtnSpace"><form:button id="bizsite_reassignTask" name="bizsite_reassignTask" link="REASSIGN_LABEL" resourceType="RESOURCE"/> </td>
</bizsolo:isAssigned></tr>
</table>
</td>
</tr>
</table>
</div>

  
                    <div id="resizablepanel" style="display:none">
                        <div class="hd">Alert Dialog</div>
                        <div class="bd"></div>
                        <div class="ft"></div>
                    </div> 
<div id="southDiv" style="height:0px;display:none;"></div></form>
</body>

<script language="JavaScript">
<!--
function beforeInitControls() {
}
-->
</script>
<script language="JavaScript">
<!--
function userValidationJavascript() {
return true;
}
-->
</script>
<sbm:dataSources appName="RGICL_MotorUW_App" appType="bizlogic">
</sbm:dataSources>
<script language="JavaScript">
<!---->
</script>
<!--Initialize extensible widgets.-->
<script language="JavaScript">
<!--
var _dateFormats = {date:'<%=bean.getPropString(PublicResources.JS_CALENDAR_DATE_FORMAT)%>', dateOnly:'<%=bean.getPropString(PublicResources.JS_CALENDAR_DATE_ONLY_FORMAT)%>'};

var allWidgets = [{widget:'textField1', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'AgentCode', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'AgentCode', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField2', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'ApprovalAuthority', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'ApprovalAuthority', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField3', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'BASCode', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'BASCode', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField4', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'branchCode', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'branchCode', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField5', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'BSMBlazeRemark', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'BSMBlazeRemark', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField6', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'BSMRemarks', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'BSMRemarks', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField7', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CallEndDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CallEndDate', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField8', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CallStartDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CallStartDate', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField9', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CallStatus', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CallStatus', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField10', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'Channel', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'Channel', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField11', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CI_UW_Queue', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CI_UW_Queue', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField12', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CreatedBy', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CreatedBy', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField13', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CUApprover', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CUApprover', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField14', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CUBlazeRemark', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CUBlazeRemark', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField15', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CUEndDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CUEndDate', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField16', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CUGroup', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CUGroup', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField17', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CUHoldDtStr', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CUHoldDtStr', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField18', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CURemarks', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CURemarks', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField19', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CUStartDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CUStartDate', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField20', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'CUStatus', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'CUStatus', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'checkBox1', bound:'true', editable:'true', type:'sbm.checkbox', source: {type:'DATASLOT', dataSlotName:'gbTPA', dataSlotType:'BOOLEAN'}, target:{type:'DATASLOT', dataSlotName:'gbTPA', dataSlotType:'BOOLEAN'}, dsType:'BOOLEAN', service:'false'},
{widget:'textField21', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'HealthProcess', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'HealthProcess', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField22', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'HealthUW', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'HealthUW', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'checkBox2', bound:'true', editable:'true', type:'sbm.checkbox', source: {type:'DATASLOT', dataSlotName:'isTpaUpdated', dataSlotType:'BOOLEAN'}, target:{type:'DATASLOT', dataSlotName:'isTpaUpdated', dataSlotType:'BOOLEAN'}, dsType:'BOOLEAN', service:'false'},
{widget:'textField23', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'LOB', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'LOB', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField24', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'MiscQueue', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'MiscQueue', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField25', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'OpsTeam', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'OpsTeam', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField26', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'PA_UW_Queue', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'PA_UW_Queue', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField27', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'PackageQueue', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'PackageQueue', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField28', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'ProductCode', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'ProductCode', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField29', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'proposalNumber', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'proposalNumber', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField30', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'QuoteNo', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'QuoteNo', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'checkBox3', bound:'true', editable:'true', type:'sbm.checkbox', source: {type:'DATASLOT', dataSlotName:'skipCUActivity', dataSlotType:'BOOLEAN'}, target:{type:'DATASLOT', dataSlotName:'skipCUActivity', dataSlotType:'BOOLEAN'}, dsType:'BOOLEAN', service:'false'},
{widget:'textField31', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'skipOPS', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'skipOPS', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField32', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'SuspendDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'SuspendDate', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField33', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'SuspendStatus', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'SuspendStatus', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField34', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'TAT', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'TAT', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField35', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'TravelQueue', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'TravelQueue', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField36', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWApprover', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWApprover', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField37', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWBlazeRemark', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWBlazeRemark', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField38', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWEndDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWEndDate', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField39', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWGroup', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWGroup', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField40', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWHoldDtStr', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWHoldDtStr', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField41', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWRemarks', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWRemarks', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField42', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWStartDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWStartDate', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField43', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'UWStatus', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'UWStatus', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField44', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'WCQueue', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'WCQueue', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField45', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'BusinessType', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'BusinessType', dataSlotType:'STRING'}, dsType:'STRING', service:'false'}
];
var businessObjects = [];
var formWidgetHandler;

sbm.utils.onDOMReady = function() {
YAHOO.util.Event.onDOMReady(function(){
formWidgetHandler = new FormWidgetHandler(allWidgets,null,{processName:'RGICL_MotorUW_App',processType:'bizlogic',maxMultiLineLength:${maxMultiLineLength},adapletCache:{'user':''}},'<%=request.getParameter(BizSoloRequest.BSS_FIID)%>');
 });
 }
Ext.onReady(function(){
 var task = new Ext.util.DelayedTask(function(){
});
  task.delay(500);
  var viewport = new Bm.util.BmViewport('',{resultComponentXtype:'container'});

});

   
    scrollToErrors = function() {
        var errorsDiv = document.getElementById('errors');
        if(errorsDiv !== null) {
            errorsDiv.scrollIntoView();
        }
    }
    sbm.utils.onFormSubmit = function() {
        if(!formWidgetHandler.validateWidgets()) {
            scrollToErrors();
            return false;
        }
        try{
            if(!userValidationJavascript()) {
                scrollToErrors();
                return false;
            }              
            sbm.utils.handleFormSubmit();
        }catch(e){
            scrollToErrors();
            return false;
        }

                            document.form.action='<%=response.encodeURL("WC_ACTIVITY.jsp")%>';
         if(allWidgets.length > 0)formWidgetHandler.saveDataSlots();
         return true;
}
-->
</script>

</html>