
CREATE TABLE BR_PROJECT (
    PROJECT_ID           BIGINT IDENTITY NOT NULL PRIMARY KEY,
    PROJECT_NAME         NVARCHAR(64) NOT NULL,
    PROJECT_VERSION      NUMERIC(3) NOT NULL,
    DESCRIPTION          NVARCHAR(512) NULL,
    PROJECT_STATUS       NVARCHAR(12) NOT NULL,
    PROJECT_CATEGORY     NVARCHAR(64) NULL,
    CREATED_BY           NVARCHAR(128) NULL,       
    CREATED_DATE         DATETIME NULL,
    MODIFIED_BY          NVARCHAR(128) NULL,
    MODIFIED_DATE        DATETIME NULL,
);

CREATE UNIQUE INDEX IX_BR_PROJECT_1 ON BR_PROJECT (
    PROJECT_NAME, 
    PROJECT_VERSION
);


CREATE TABLE BR_RULESET (
    RULESET_ID           BIGINT IDENTITY NOT NULL PRIMARY KEY,
    RULESET_NAME         NVARCHAR(64) NULL,
    DESCRIPTION          NVARCHAR(512) NULL,
    RULE_TYPE            NVARCHAR(4) NULL,
    RULE_CONTENT         VARBINARY NULL,
    PROJECT_ID           BIGINT NOT NULL,
    RULESET_STATUS       NVARCHAR(12) NOT NULL,
    RULESET_CATEGORY     NVARCHAR(64) NULL,
    PROPERTIES           VARBINARY NULL,
    CREATED_BY           NVARCHAR(128) NULL,       
    CREATED_DATE         DATETIME NULL,
    MODIFIED_BY          NVARCHAR(128) NULL,
    MODIFIED_DATE        DATETIME NULL,
);


CREATE UNIQUE INDEX IX_BR_RULESET_1 ON BR_RULESET(
    PROJECT_ID, 
    RULESET_NAME
);


CREATE TABLE BR_EXEC_SET (
    EXEC_SET_ID         BIGINT IDENTITY NOT NULL PRIMARY KEY,
    URI                 NVARCHAR(256) NOT NULL,
    DESCRIPTION         NVARCHAR(512) NULL,
    CREATED_BY          NVARCHAR(128) NULL,
    CREATED_DATE        DATETIME NULL,
    MODIFIED_BY         NVARCHAR(128) NULL,
    MODIFIED_DATE       DATETIME NULL
);

CREATE UNIQUE INDEX IX_BR_EXEC_SET_1 ON BR_EXEC_SET (
    URI
);

CREATE TABLE BR_EXEC_SET_RULESET_REL (
    EXEC_SET_ID         BIGINT NOT NULL,
    RULESET_ID        	BIGINT NOT NULL,
    CONSTRAINT BR_ES_RS_PKEY PRIMARY KEY(EXEC_SET_ID, RULESET_ID)
);

CREATE INDEX IX_ES_RS_REL_ESID
 ON BR_EXEC_SET_RULESET_REL (EXEC_SET_ID);

CREATE INDEX IX_ES_RS_REL_RSID
 ON BR_EXEC_SET_RULESET_REL (RULESET_ID);
