<%--  This JSP has been generated by using from xsl version 9.0 at Wed Mar 09 17:53:46 IST 2022 --%>
<!DOCTYPE html>
<html xmlns:sbm="http://www.savvion.com/sbm" xmlns:bizsolo="http://www.savvion.com/sbm/BizSolo" xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:xalan="http://xml.apache.org/xalan" xmlns:fn="http://www.w3.org/2005/02/xpath-functions" xmlns:sfe="http://www.savvion.com/sbm/sfe" xmlns:c="http://java.sun.com/jsp/jstl/core">
<head><META http-equiv="Content-Type" content="text/html; charset=utf-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge">

<%@ page contentType="text/html; charset=UTF-8" %>
<%@ page import="com.savvion.BizSolo.Server.*,com.savvion.BizSolo.beans.*,com.savvion.sbm.util.DatabaseMapping,java.util.Vector,java.util.Locale" %>
<%@ page import="com.savvion.sbm.bizsolo.util.session.*,java.net.*" %>
<%@ page errorPage="/BizSolo/common/jsp/expcontroller.jsp" %>
<%@ taglib uri="/BizSolo/common/tlds/bizsolo.tld" prefix="bizsolo" %>
<%@ taglib uri="/bpmportal/tld/bpmportal.tld" prefix="sbm" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib prefix="form" tagdir="/WEB-INF/tags/form"%>
<%@ taglib prefix="sfe" uri="http://jmaki/v1.0/jsp" %>
  <jsp:useBean id="bizManage" class="com.savvion.sbm.bizmanage.api.BizManageBean" scope="session"></jsp:useBean>
  <jsp:useBean id="bean" class="com.savvion.BizSolo.beans.Bean" scope="session"></jsp:useBean>
  <jsp:useBean id="factoryBean" class="com.savvion.BizSolo.beans.EPFactoryBean" scope="session"></jsp:useBean>
  <jsp:useBean id="bizSite" class="com.savvion.sbm.bpmportal.bizsite.api.BizSiteBean" scope="session"></jsp:useBean>
<%! String _PageName = "ApproveExcessRefund"; %>
<%! String __webAppName = "ICMExcessRefundApp"; %>
<% pageContext.setAttribute( "contextPath", request.getContextPath()+"/"); %>
<% pageContext.setAttribute( "maxMultiLineLength", DatabaseMapping.self().getSQLSize(java.lang.String.class));  %>
<%java.util.List<String> priorities = com.savvion.sbm.bpmportal.util.PortalUtil.self().getPriorities();%>
<% pageContext.setAttribute( "_priorities",priorities); %>
<bizsolo:if test='<%=_PageName.equals(request.getParameter("_PageName")) %>'>
    <bizsolo:setDS name="PayeeName,Branch,ClassName,InstrumentFrom,InsuredName,PayTo,PrintLocation,Product,ProposalID,RefundAmount,RefundType,RequestDate,RequestedBy,TransactionId,ApproverStatus,Remarks"></bizsolo:setDS>
    <bizsolo:choose>
<bizsolo:when test='<%=request.getParameter("bizsite_reassignTask") !=null %>'>
      <bizsolo:initDS name="performer" param="bizsite_assigneeName" hexval="FALSE"></bizsolo:initDS>
      <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKReassignWI" perfMethod="commit" mode="BizSite" dsi="TransactionId,RequestedBy,RequestDate,RefundType,RefundAmount,ProposalID,Product,PrintLocation,PayTo,InsuredName,InstrumentFrom,ClassName,Branch,PayeeName" dso="Remarks,ApproverStatus"></bizsolo:executeAction>
</bizsolo:when>
<bizsolo:when test='<%=request.getParameter("bizsite_saveTask") !=null %>'>
      <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKUpdateDS" perfMethod="commit" mode="BizSite" dsi="Remarks,ApproverStatus"></bizsolo:executeAction>
</bizsolo:when>
    <bizsolo:otherwise>
      <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKSetDS" perfMethod="commit" mode="BizSite" dsi="Remarks,ApproverStatus" res=""></bizsolo:executeAction>
      </bizsolo:otherwise>
    </bizsolo:choose>
<% /* Workaround, retAddr will disappear in the future */ %>
<% String retAddr = bean.getPropString("returnPage"); %>
<% if(retAddr != null) { %>
<bizsolo:redirectURL page="<%= retAddr %>"/>
<% } %>
</bizsolo:if>
<bizsolo:if test='<%= ! _PageName.equals(request.getParameter("_PageName")) %>'>
    <bizsolo:initApp mode="BizSite" name="ICMExcessRefundApp"></bizsolo:initApp>
<bizsolo:initDS name="PayeeName" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="Branch" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="ClassName" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="InstrumentFrom" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="InsuredName" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="PayTo" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="PrintLocation" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="Product" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="ProposalID" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="RefundAmount" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="RefundType" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="RequestDate" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="RequestedBy" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="TransactionId" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="ApproverStatus" type="STRING"></bizsolo:initDS>
<bizsolo:initDS name="Remarks" type="STRING"></bizsolo:initDS>
    <bizsolo:executeAction epClassName="com.savvion.BizSolo.beans.PAKGetDS" perfMethod="commit" mode="BizSite" dso="Remarks,ApproverStatus,TransactionId,RequestedBy,RequestDate,RefundType,RefundAmount,ProposalID,Product,PrintLocation,PayTo,InsuredName,InstrumentFrom,ClassName,Branch,PayeeName"></bizsolo:executeAction>
</bizsolo:if>

<title>ApproveExcessRefund</title>
<%boolean isStandaloneBS = (bizManage == null || bizManage.getName() == null || "".equals(bizManage.getName()) || bizManage.getLocale() == null);Locale myLocale = (!isStandaloneBS) ? bizManage.getLocale() : request.getLocale();%>
<!-- Javascript -->
<script language="JavaScript"> var getLocalizedString = parent.getLocalizedString; </script>
<form:includes contextPath="${contextPath}"/>
<script language="JavaScript">
     
      var isIFrame = <%= (PublicResources.INTERACTIVE_MODE.equalsIgnoreCase(bean.getPropString(PublicResources.MODE)) || PublicResources.SLAVE_MODE.equalsIgnoreCase(bean.getPropString(PublicResources.MODE))) ? true : false %>;
      

    function getContextPath(){
        return "<%=request.getContextPath()%>";
    }
</script>


<sbm:setLocale value="<%= bizManage.getLocale() %>"></sbm:setLocale>
<% try{ %><sbm:setBundle scope="page" basename="ICMExcessRefundApp/properties/ICMExcessRefundApp"></sbm:setBundle><% } catch(Exception e){}%>
<bizsolo:getApplicationResources baseName="ICMExcessRefundApp/properties/ICMExcessRefundApp"/></head>
<body class="apbody yui-skin-sam" onLoad="setCheckBoxStyleForIE();hideControls();beforeInitControls();initControls();initTabs();sbm.utils.onDOMReady();">
<form method="post" name="form" onsubmit="return sbm.utils.onFormSubmit();">
<div id="northDiv" style="height:0px;display:none;"><bizsolo:xsrf/></div><% /* Workaround, activityName will disappear in the future */ %>
<% String activityName = bean.getPropString("workitemName"); %>
<div id="resultDiv">
<div style='visibility:hidden;display:none' class='vBoxClass' name='errors' id='errors'></div>
<input name="_PageName" type="hidden" value="ApproveExcessRefund">
<%if(bean.getPropString("workitemName") != null) {%><input name="_WorkitemName" type="hidden" value="<%= URLHexCoder.encode(bean.getPropString("workitemName")) %>"/><input name="_WorkitemId" type="hidden" value="<%= bean.getPropLong("workitemId") %>"/><%}%>
<input name="bizsite_pagetype" type="hidden" value="activity">
<input name="_ProcessTemplateName" type="hidden" value='<%=bean.getPropString("ptName")%>'>
<input name="_yahoo_flow_button" type="hidden" value=''>
<!-- Content --> 

    
<!-- Header -->

                    <bizsolo:choose><bizsolo:when test='<%=bean.getPropString(\"workitemName\") != null %>'><table width="100%" cellspacing="0" cellpadding="0" border="0">
<tr>
<td class="ApSegTblInBg">
<table width="100%" cellpadding="4" align="center" cellspacing="0" border="0">
<tr>

<td class="ApSegTitle" align="center"><bizsolo:choose><bizsolo:when test='<%=bean.getPropString(\"workitemName\") != null %>'><bizsolo:getDS name="workitemName"></bizsolo:getDS></bizsolo:when><bizsolo:otherwise><%=_PageName%></bizsolo:otherwise></bizsolo:choose></td>
</tr>
</table>
<table class="ApSegDataTbl" width="100%" cellspacing="1" cellpadding="4" border="0">
<tr>
<td width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_INSTRUCTION_LABEL"></bizsolo:getLabel></td><td width="85%" class="ApSegGenData" colspan="5"><sbm:message key="workstep.ApproveExcessRefund.instruction" escapeLine="true"></sbm:message></td>
</tr>
<tr>
<td width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_PRIORITY_LABEL"></bizsolo:getLabel></td><td width="15%" class="ApSegGenData"><bizsolo:getDS name="bizsite_priority"></bizsolo:getDS></td>
<td width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_STARTDATE_LABEL"></bizsolo:getLabel></td><td width="15%" class="ApSegGenData"><bizsolo:getDS name="bizsite_startDate"></bizsolo:getDS></td>
<td width="15%" class="ApSegGenLabel"><bizsolo:getLabel type="RESOURCE" name="BIZSITE_DUEDATE_LABEL"></bizsolo:getLabel></td><td width="15%" class="ApSegGenData"><bizsolo:getDS name="bizsite_dueDate"></bizsolo:getDS></td>
</tr>
</table>
</td>
</tr>
</table></bizsolo:when></bizsolo:choose>

    <table align="left" cellpadding="0" cellspacing="0" class="blue_shade_reliance_red tr td" id="table3" width="100%">
      <colgroup span="1">
        <col width="100%" span="1">
      </colgroup>
      <tbody>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <bizsolo:link rel="stylesheet"/>

<link rel="stylesheet" type="text/css" href="<c:out value='${contextPath}'/>ebmsapps/ICMExcessRefundApp/css/rgic01.css">

<div style='text-align: center; display: block'>ICM Excess Refund Approval</div>
          </td>
        </tr>
      </tbody>
    </table>
    <br clear="all">
<table align="left" cellpadding="0" cellspacing="0" class="blue_shade_reliance_blue tr td" id="table1" width="100%">
      <colgroup span="1">
        <col width="25%" span="1">
        <col width="25%" span="1">
        <col width="25%" span="1">
        <col width="25%" span="1">
      </colgroup>
      <tbody>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Payee Name:</label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField1" args="{'type':'text', 'size':50, 'maxlength':256, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Branch:</label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField2" args="{'type':'text', 'size':50, 'maxlength':256, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Class:</label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField3" args="{'type':'text', 'size':50, 'maxlength':256, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Instrument From:</label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField4" args="{'type':'text', 'size':50, 'maxlength':256, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Insured Name:</label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField5" args="{'type':'text', 'size':50, 'maxlength':256, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Pay To:</label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField6" args="{'type':'text', 'size':50, 'maxlength':256, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Print Location:</label>
          </td>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField7" args="{'type':'text', 'size':50, 'maxlength':256, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Product:</label>
          </td>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField8" args="{'type':'text', 'size':50, 'maxlength':256, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Proposal ID:</label>
          </td>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField9" args="{'type':'text', 'size':50, 'maxlength':64, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Refund Amount:</label>
          </td>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField10" args="{'type':'text', 'size':50, 'maxlength':64, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Refund Type:</label>
          </td>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField11" args="{'type':'text', 'size':50, 'maxlength':64, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Request Date:</label>
          </td>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField12" args="{'type':'text', 'size':20, 'maxlength':64, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
        <tr>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Requested By:</label>
          </td>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField13" args="{'type':'text', 'size':50, 'maxlength':256, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Transaction Id:</label>
          </td>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textfield" id="textField15" args="{'type':'text', 'size':20, 'maxlength':64, 'readonly':true, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
      </tbody>
    </table>
    <br clear="all">
<table align="left" cellpadding="0" cellspacing="0" class="blue_shade_reliance_blue tr td" id="table2" width="100%">
      <colgroup span="1">
        <col width="50%" span="1">
        <col width="50%" span="1">
      </colgroup>
      <tbody>
        <tr>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Approver Status:</label>
          </td>
          <td align="left" class="ApSegDataVal" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.combobox" id="comboBox1" args="{'size':20, 'readonly':false, 'visible':true, 'disabled':false, 'cascade':false, 'level':0, 'validationType':'none', 'validation':{}, 'toolTip':'', 'tabOrder':'0'}" value="[{'selected':true,'value':'Select','label':'Select'},{'selected':false,'value':'Approved','label':'Approved'},{'selected':false,'value':'Rejected','label':'Rejected'}]" />

          </td>
        </tr>
        <tr>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <label>Remarks:</label>
          </td>
          <td align="left" class="(default)" id="" style="text-align:left;vertical-align:top" valign="top" rowspan="1" colspan="1">
            <sfe:widget name="sbm.textarea" id="textField14" args="{'wrap':'Soft', 'rows':6, 'cols':71, 'visible':true, 'readonly':false, 'disabled':false, 'validationType':'none', 'validation':{ 'counterId':'textField14_counter_span'}, 'toolTip':'', 'tabOrder':'0'}" />

          </td>
        </tr>
      </tbody>
    </table>
    

</div>
<!-- Footer -->

<div id="cmdDiv" style="height:46px;">
<table width="100%" height="100%" cellpadding="0" align="center" cellspacing="0" border="0">
<tr align="center">
<td class="ApButtonDarkBg" width="63%">
<table border="0" cellspacing="0" cellpadding="0">
<tr>
<td class="ApBtnSpace">
<bizsolo:isNotSuspended><form:button id="bizsite_completeTask" name="bizsite_completeTask" link="COMPLETE_LABEL" resourceType="RESOURCE"/> </bizsolo:isNotSuspended></td>
<td class="ApBtnSpace">
<form:button id="bizsite_saveTask" name="bizsite_saveTask" link="SAVE_LABEL" resourceType="RESOURCE"/> </td>
<bizsolo:isAssigned></bizsolo:isAssigned><td class="ApBtnSpace">
<form:button id="bizsite_reset" name="bizsite_reset" link="RESET_LABEL" onclick="sbm.utils.reset" resourceType="RESOURCE"/> </td>
<td class="ApBtnSpace">
<form:button id="btn-cancel" name="btn-cancel" link="CANCEL_LABEL" onclick="sbm.utils.cancel" resourceType="RESOURCE"/> </td>
<bizsolo:isAssigned><td class="ApBtnSpace"><input class="ApInptTxt" type="text" name="bizsite_assigneeName" size="20"></td><td class="ApBtnSpace"><a href="javascript://" onClick="setUserControl(document.form.bizsite_assigneeName);searchUser()"><img width="16" height="16" border="0" title="Search" src="<c:out value='${contextPath}'/>bpmportal/css/app<%= bizManage.getTheme() %>/images/icon_edit_user_search_single.gif"></img></a></td><td class="ApBtnSpace"><form:button id="bizsite_reassignTask" name="bizsite_reassignTask" link="REASSIGN_LABEL" resourceType="RESOURCE"/> </td>
</bizsolo:isAssigned></tr>
</table>
</td>
</tr>
</table>
</div>

  
                    <div id="resizablepanel" style="display:none">
                        <div class="hd">Alert Dialog</div>
                        <div class="bd"></div>
                        <div class="ft"></div>
                    </div> 
<div id="southDiv" style="height:0px;display:none;"></div></form>
</body>

<script language="JavaScript">
<!--
function beforeInitControls() {
}
-->
</script>
<script language="JavaScript">
<!--
function userValidationJavascript() {
return true;
}
-->
</script>
<sbm:dataSources appName="ICMExcessRefundApp" appType="bizlogic">
</sbm:dataSources>
<script language="JavaScript">
<!--
 function button_complete_onClick(eventContext){
{
var v1 = document.getElementById('textField14').value;
var v2 = document.getElementById('comboBox1').value;
if(v1.replace(/^\s+|\s+$/g, '') ==null || v1.replace(/^\s+|\s+$/g, '') =="" || v2=="Select")
{
alert('Please select appropriate action to be taken and add appropriate remark');
return false;
};
}}

-->
</script>
<!--Initialize extensible widgets.-->
<script language="JavaScript">
<!--
var _dateFormats = {date:'<%=bean.getPropString(PublicResources.JS_CALENDAR_DATE_FORMAT)%>', dateOnly:'<%=bean.getPropString(PublicResources.JS_CALENDAR_DATE_ONLY_FORMAT)%>'};

var allWidgets = [{widget:'textField1', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'PayeeName', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'PayeeName', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField2', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'Branch', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'Branch', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField3', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'ClassName', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'ClassName', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField4', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'InstrumentFrom', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'InstrumentFrom', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField5', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'InsuredName', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'InsuredName', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField6', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'PayTo', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'PayTo', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField7', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'PrintLocation', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'PrintLocation', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField8', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'Product', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'Product', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField9', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'ProposalID', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'ProposalID', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField10', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'RefundAmount', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'RefundAmount', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField11', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'RefundType', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'RefundType', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField12', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'RequestDate', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'RequestDate', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField13', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'RequestedBy', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'RequestedBy', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'textField15', bound:'true', editable:'false', type:'sbm.textfield', source: {type:'DATASLOT', dataSlotName:'TransactionId', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'TransactionId', dataSlotType:'STRING'}, dsType:'STRING', service:'false'},
{widget:'comboBox1', bound:'false', editable:'true', type:'sbm.combobox', source: {type:'STATIC'}, target:{type:'DATASLOT', dataSlotName:'ApproverStatus', dataSlotType:'STRING'}, dsType:'', service:'false'},
{widget:'textField14', bound:'true', editable:'true', type:'sbm.textarea', source: {type:'DATASLOT', dataSlotName:'Remarks', dataSlotType:'STRING'}, target:{type:'DATASLOT', dataSlotName:'Remarks', dataSlotType:'STRING'}, dsType:'STRING', service:'false'}
];
var businessObjects = [];
var formWidgetHandler;

sbm.utils.onDOMReady = function() {
YAHOO.util.Event.onDOMReady(function(){
formWidgetHandler = new FormWidgetHandler(allWidgets,null,{processName:'ICMExcessRefundApp',processType:'bizlogic',maxMultiLineLength:${maxMultiLineLength},adapletCache:{'user':''}},'<%=request.getParameter(BizSoloRequest.BSS_FIID)%>');
 });
 }
Ext.onReady(function(){
 var task = new Ext.util.DelayedTask(function(){
});
  task.delay(500);
  var viewport = new Bm.util.BmViewport('',{resultComponentXtype:'container'});

});

   
    scrollToErrors = function() {
        var errorsDiv = document.getElementById('errors');
        if(errorsDiv !== null) {
            errorsDiv.scrollIntoView();
        }
    }
    sbm.utils.onFormSubmit = function() {
        if(!formWidgetHandler.validateWidgets()) {
            scrollToErrors();
            return false;
        }
        try{
            if(!userValidationJavascript()) {
                scrollToErrors();
                return false;
            }              
            sbm.utils.handleFormSubmit();
        }catch(e){
            scrollToErrors();
            return false;
        }

                            document.form.action='<%=response.encodeURL("ApproveExcessRefund.jsp")%>';
         if(allWidgets.length > 0)formWidgetHandler.saveDataSlots();
         return true;
}
-->
</script>

</html>