
CREATE TABLE BR_PROJECT (
    PROJECT_ID          INTEGER NOT NULL,
    PROJECT_NAME        VARCHAR2(64) NOT NULL,
    PROJECT_VERSION     NUMBER(3) NOT NULL,
    DESCRIPTION         VARCHAR2(512) NULL,
    PROJECT_STATUS      VARCHAR2(12) NOT NULL,
    PROJECT_CATEGORY    VARCHAR2(64) NULL,    
    CREATED_BY          VARCHAR2(128) NULL,
    CREATED_DATE        DATE NULL,
    MODIFIED_BY         VARCHAR2(128) NULL,
    MODIFIED_DATE       DATE NULL,
    CONSTRAINT BR_PROJECT_PKEY PRIMARY KEY(PROJECT_ID)
);

CREATE UNIQUE INDEX IX_BR_PROJECT_1 ON BR_PROJECT (
    PROJECT_NAME, 
    PROJECT_VERSION
);

CREATE SEQUENCE BR_PROJECT_ID_SEQ NOCACHE;


CREATE TABLE BR_RULESET (
    RULESET_ID          INTEGER NOT NULL,
    RULESET_NAME        VARCHAR2(64) NOT NULL,
    DESCRIPTION         VARCHAR2(512) NULL,
    RULE_TYPE           VARCHAR2(4) NULL,
    RULE_CONTENT        BLOB NULL,
    PROJECT_ID          INTEGER NOT NULL,
    RULESET_STATUS      VARCHAR2(12) NOT NULL,
    RULESET_CATEGORY    VARCHAR2(64) NULL,
    PROPERTIES          BLOB NULL,
    CREATED_BY          VARCHAR2(128) NULL,
    CREATED_DATE        DATE NULL,
    MODIFIED_BY         VARCHAR2(128) NULL,
    MODIFIED_DATE       DATE NULL,
    CONSTRAINT BR_RULESET_PKEY PRIMARY KEY(RULESET_ID)
);

CREATE UNIQUE INDEX IX_BR_RULESET_1 ON BR_RULESET (
    PROJECT_ID, 
    RULESET_NAME
);

CREATE INDEX IX_BR_RULESET_PROJECT_ID ON BR_RULESET(
    PROJECT_ID
);

CREATE SEQUENCE BR_RULESET_ID_SEQ NOCACHE;


CREATE TABLE BR_EXEC_SET (
    EXEC_SET_ID         INTEGER NOT NULL,
    URI                 VARCHAR2(256) NOT NULL,
    DESCRIPTION         VARCHAR2(512) NULL,
    CREATED_BY          VARCHAR2(128) NULL,
    CREATED_DATE        DATE NULL,
    MODIFIED_BY         VARCHAR2(128) NULL,
    MODIFIED_DATE       DATE NULL,
    CONSTRAINT BR_EXEC_SET_PKEY PRIMARY KEY(EXEC_SET_ID)
);

CREATE UNIQUE INDEX IX_BR_EXEC_SET_1 ON BR_EXEC_SET (
    URI
);

CREATE SEQUENCE BR_EXEC_SET_ID_SEQ NOCACHE;

CREATE TABLE BR_EXEC_SET_RULESET_REL (
    EXEC_SET_ID         INTEGER NOT NULL,
    RULESET_ID        	INTEGER NOT NULL,
	CONSTRAINT BR_ES_RS_UNIQUE UNIQUE (EXEC_SET_ID, RULESET_ID)
);

CREATE INDEX IX_ES_RS_REL_ESID
 ON BR_EXEC_SET_RULESET_REL (EXEC_SET_ID);

CREATE INDEX IX_ES_RS_REL_RSID
 ON BR_EXEC_SET_RULESET_REL (RULESET_ID);




