
DROP TABLE BR_RULESET;
DROP TABLE BR_PROJECT;
DROP TABLE BR_EXEC_SET;
DROP TABLE BR_EXEC_SET_RULESET_REL;

DROP SEQUENCE BR_PROJECT_ID_SEQ;
DROP SEQUENCE BR_RULESET_ID_SEQ;
DROP SEQUENCE BR_EXEC_SET_ID_SEQ;
